### ISSUE TITLE
How to add export output vars for future steps in pipeline?

### ISSUE THREAD

**Issue by dumblerod** [charleszipp/azure-pipelines-tasks-terraform#102]
Hopefully simple question: How can I add export output vars for future steps in pipeline?

I looked through the docs and there are screenshots of the output variables as a field on the task, but when I create one through the console, I don't see that field on the task generator.

**Comment by charleszipp** [comment]
Hey @dumblerod the pattern I typically follow for this is to have the terraform templates write the values you need to something like azure keyvault (or wherever you store configuration parameters). Then, before executing the tasks that follow your terraform deployment, i use the keyvault task to read those to env vars that can then be fed into the tasks.

I typically recommend separating the terraform deployment and application deployments (which is what im assuming are your future steps) into different stages. The approach i suggested typically works well for that setup.

If this recommendation doesnt fit your usecase, please provide some more detail about the setup of your pipeline so I can understand if there may be another option.

**Comment by richardswinbank** [comment]
I'm having exactly this problem but with the Key Vault itself. I'm using the CLI task (thanks btw!) to Terraform a disposable dev environment (a resource group containing some SQL assets, a data factory and its own key vault holding connection strings etc). 

Because the environments are disposable their names are determined on-the-fly - so it would be nice to be able to pass the name of the key vault out of the terraform apply, so that I can use it later to obtain a connection string to deploy code to the SQL server databases.

**Comment by charleszipp** [comment]
Thanks for providing that context @richardswinbank! That helps me understand why the key vault task wont solve your issue.

**Comment by charleszipp** [comment]
@dumblerod @richardswinbank im thinking we could solve this by adding support for the output command. Here is the scenarios I think we could support using the [output command](https://www.terraform.io/docs/commands/output.html)

## Export Outputs as Pipeline Vars

When the output command runs, it creates pipeline variables from the output variables produced by the templates. Assuming we have the following outputs defined in the template...

```terraform
output "lb_address" {
  value = "${aws_alb.web.public_dns}"
}

output "instance_ips" {
  value = ["${aws_instance.web.*.public_ip}"]
}
```
Running output command from the task would then create the following pipeline variables
TF_OUT_LB_ADDRESS
TF_OUT_INSTANCE_IPS

## Out of Scope / Potential Follow-up Features
The following will not be supported in the initial changes but, may be added later.
### Export Only Specified Outputs
Export only outputs configured by the user to pipeline variables
### Export Sensitive Outputs
Terraform will redact any output that is marked as sensitive. Therefore, sensitive outputs will not be supported.
```terraform
output "password" {
  sensitive = true
  value = ["${var.secret_password}"]
}
```
is emitted as 
```shell
password = <sensitive>
```

**Comment by charleszipp** [comment]
moved to #120
