### ISSUE TITLE
Standard error does not seem to be written to log

### ISSUE THREAD

**Issue by kevbite** [charleszipp/azure-pipelines-tasks-terraform#103]
When there is an issue running a `terraform plan` or `terraform apply` from the Azure DevOps task no errors are written to the logs within Azure DevOps, it looks like it's missing writing out the standard error to the log?

Here's a screenshot of a failed terraform plan operation, if I do this locally I get errors
![image](https://user-images.githubusercontent.com/5544715/74331842-6d231f80-4d8c-11ea-9286-9f3db7a95723.png)

**Comment by charleszipp** [comment]
Hey @kevbite can you verify whether or not this is still happening for you after 0.5.1 release today? With the changes in #82 / #115, that may resolve whatever was preventing stderr output before. Now the stdout/stderr should be written to the console in real time.

Closing as resolved with #115 for now.
