### ISSUE TITLE
add support for terraform show cmd

### ISSUE THREAD

**Issue by rguthriemsft** [charleszipp/azure-pipelines-tasks-terraform#104]
we have a need to store the plan as json in our pipeline for debugging purposes.  We would like to add support for TF Show so that we can use task to store the plan.

**Comment by sten-rosendahl** [comment]
Please make this work both for plans and states, and for both both remote and local use cases, optionally redirecting output to a file for it to be published an a pipeline artifact.

**Comment by charleszipp** [comment]
#84 also requested making plan available in human readable format. Author of that issue agreed this issue should satisfy what they needed.

**Comment by scott-doyland-burrows** [comment]
Would be good to have "show" actually show the output.  Agree it shows secrets - but then anyone with access to the pipelines to run the terraform extension probably has a lot of access anyway.  So doubt those users seeing the secrets would matter.
