### ISSUE TITLE
add support in terraform plan to indicate plan includes destroy operation so automation can take decision if destroy is present in plan. 

### ISSUE THREAD

**Issue by rguthriemsft** [charleszipp/azure-pipelines-tasks-terraform#105]
the terraform cli task already supports setting env variable if change is detected.  This issue is to add functionality to support indicating if a destroy operation is present in the plan.

**Comment by charleszipp** [comment]
@rguthriemsft @HadwaAbdelhalem, im thinking the implementation could be to examine the stdout returned by the exec on line [156 of the terraform-runner.ts.](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/TerraformCLI/src/terraform-runner.ts#L156)
```javascript
let result = this.terraform.execSync(<IExecSyncOptions>{
     cwd: this.command.workingDirectory
});
``` 
At the end of the plan, there is always a summary that reads like this...
```shell
Plan: X to add, X to change, X to destroy.
```
If we can parse the std out for that line and see if the destroy section is greater than 1, then i think that should tell us if there is destroy in the command.

I would make the env var name `TERRAFORM_PLAN_HAS_DESTROY` to be consistent with the other we support for change detection. If you need an example of how to set this see this [line](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/TerraformCLI/src/terraform-plan.ts#L82)

For the tests, i would check out the test we do for the detailed exit code. There are [assertion helpers](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/TerraformCLI/src/tests/terraform-plan/plan_spec.ts#L30) to verify the pipeline vars are set to a particular value. Additionally, I would use this [example](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/TerraformCLI/src/tests/terraform-plan/plan-azurerm-with-detailed-exitcode-with-changes.ts) as a guide line on how to configure the test scenario. **Be sure to include both a positive (has destroy operations) and negative (no destroy operations) test  cases.**

**Comment by charleszipp** [comment]
After talking with @rguthriemsft the plan is to see if the show command might be able to expose this more reliably via reading the json output file first. Parsing stdout will be a backup option.
