### ISSUE TITLE
Migrate ci/cd pipeline to github actions

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#119]
The current CI/CD pipelines are running off the classic build and release pipelines from azure devops. This issue is to migrate the current build and release process to use github actions. This will allow the pipeline to be accessible to contributors. It will also allow the pipelines to be modified and tested within feature branches.

**Comment by ams0** [comment]
What about Github Actions? I'd be happy to contribute on that (my first one!)

**Comment by charleszipp** [comment]
Absolutely @ams0 would be happy to see what you come up with there. That would also help make the pipeline more accessible to contributors. Thanks for the suggestion and volunteering!

Let me know if you need access to the current pipeline

**Comment by charleszipp** [comment]
Closing this as the pipeline will be moved to yaml-based multi-stage ADO pipeline. This should allow contributors to make changes to the pipeline and test in isolation.
