### ISSUE TITLE
Terraform Plan not completing

### ISSUE THREAD

**Issue by caseyhunt520** [charleszipp/azure-pipelines-tasks-terraform#121]
Terraform plan is not functioning as before in DevOps Release Pipeline. Stays on plan forever with a message "Waiting for console output from an agent..."

**Comment by charleszipp** [comment]
Hey @caseyhunt520, this error typically has to do more with the build agent than it does with the task. Especially if you are using hosted agents, there are a number of things that could cause this. It may be best to work with AzDO support team to resolve this first.

**Comment by jeffruel** [comment]
Hey @caseyhunt520, we seem to have the same symptoms since upgrading our TFS 2017 Build Agents to Azure DevOps Pipeline Agents on-prem last Week.  We you able to solve the problems ?

Jeff
