### ISSUE TITLE
Warning on terraform apply - [DEPRECATED] variable names

### ISSUE THREAD

**Issue by norelina** [charleszipp/azure-pipelines-tasks-terraform#123]
### Repro steps
Executed terraform apply using:

- Terraform v0.12.23
- provider.azurerm v2.0.0

### Expected results: 
No warnings or errors

### Actual results: 
Received the following warnings: 

1. Warning: "arm_tenant_id": [DEPRECATED] `arm_tenant_id` has been replaced by `tenant_id`
2. Warning: "arm_client_id": [DEPRECATED] `arm_client_id` has been replaced by `client_id`
3. Warning: "arm_client_secret": [DEPRECATED] `arm_client_secret` has been replaced by `client_secret`
4. Warning: "arm_subscription_id": [DEPRECATED] `arm_subscription_id` has been replaced by `subscription_id`

**Comment by favoretti** [comment]
@charleszipp Do we wanna set both for the time being and drop the `ARM_*` ones later on?

**Comment by charleszipp** [comment]
@norelina @favoretti should be resolved with #136 

I was not able to repro this in the pipelines or locally. I was using azurerm 0.2.10 and cli version 0.12.25. I suspect they have made a change recently to suppress the warnings. If you look at the terraform.tfstate file that gets created on the node where the cli runs, it pulls in both the `arm_*` configs as well as the ones in the current docs. 

I went ahead and updated to be consistent with whats documented. Verified this still works as expected. 

If users happen to be using older versions that dont support the latest config names, then they can use the self-configured option @favoretti added along with secure .env files to configure in a way thats compatible with the version they need.

**Comment by charleszipp** [comment]
Reopening this issue as the changes that were made for #136 had to be rolled back. See #139 for details. TLDR; for those on 0.11 or lower, this change causes init to fail.

Will need to make this change so that the existing configs are still used when terraform 0.11 or lower is being used.

**Comment by favoretti** [comment]
@charleszipp there's no easy way to fetch used TF version in TFCli task, or am I overlooking something obvious?

**Comment by charleszipp** [comment]
@favoretti at the beginning of each execution, we run `terraform version`. That will write the version to stdout. To make this work, we need to capture the version from output of executing that command. Then, pass it as a parameter into the subsequent command. To get it into the command (since we pull the inputs currently from the tasks lib), it would probably need to be set as an env variable. 

After accomplishing that, the command could access the version and make decisions about how to execute based on the discovered version. 

Does that make sense?

**Comment by timja** [comment]
FYI these values have now been removed in 0.15 (also see https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/268)

**Comment by charleszipp** [comment]
Fixed with 0.6.20 in #273
