### ISSUE TITLE
This task is still listed as Pre-View version

### ISSUE THREAD

**Issue by SherinMirza** [charleszipp/azure-pipelines-tasks-terraform#124]
This task is still listed as Preview.
When is the prod version available and is it going to be a paid plugin?

**Comment by charleszipp** [comment]
@SherinMirza this extension will not convert to paid plugin. Despite what the version indicates, many people are using this for production systems. The TerraformCLI task is executed thousands of times on average every day all across the world. 

With that said however, as with many open source project with no express support sla's. This is the reason the extension is free. I am have a few contributors that help here and there but, I am the sole maintainer of the project. I cannot guarantee issues found will be fixed immediately or that enhancements will be added on a routine basis.
