### ISSUE TITLE
Secure Variables File management link uses fixed azure devops project link

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#133]
The current configuration of `secureVarsFile` within the TerraformCLI task likely prevents users from being able to manage secure files from the task

The `ManageLink` is set to a fixed azure devops project. 

If there are tokens/variables that can be used to represent the current AzDO instance and project in which the task exists, those should be used. If such tokens/variables do not exist, then disable management (i.e. `"EnableManagement": "false"` and remove `ManagementLink`)

```json
{
    "name": "secureVarsFile",
    "type": "secureFile",
    "label": "Secured Variables File (Secrets)",
    "required": false,
    "helpMarkDown": "Pick a secure file from Azure DevOps Secure Files. This option is used to pass terraform variables using a tfvars or .env file stored in secure files.",
    "groupName": "variables",
    "properties": {
        "EnableManage": "True",
        "ManageLink": "https://dev.azure.com/chzipp/azure-pipelines-tasks-terraform/_library?itemType=SecureFiles"
    }
}
```

**Comment by favoretti** [comment]
Had a quick look in other tasks over the world, couldn't find anything like that..
