### ISSUE TITLE
Yaml pipeline throws error on terraform init command.

### ISSUE THREAD

**Issue by verodhi** [charleszipp/azure-pipelines-tasks-terraform#143]
I have been using classic pipeline (UI generated) and it has been working fine.
Recently, I moved to YAML pipeline so that I can version control it.

Specifically, I am using the deployment job that pipeline provides ([reference here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops))

Here is the snippet, it is based on what the YAML version of classic pipeline provides.

`

            - task: TerraformTaskV1@0

              inputs:

                provider: 'azurerm'

                command: 'init'

                workingDirectory: 'tfmain'

                commandOptions: '--no-color'

                backendServiceArm: 'Pay-As-You-Go (********************************)'

                backendAzureRmResourceGroupName: 'InfrastructureState'

                backendAzureRmStorageAccountName: 'cdl7tfaccount'

                backendAzureRmContainerName: 'terraform-state'

                backendAzureRmKey: 'terraform.tfstate'`

It errors out with the following message:
`##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/0.12.26/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/0.12.26/x64/terraform ENOENT`

Debugging:
I checked the raw logs of both classic pipeline and YAML pipeline, both are running the same exact command.

**Comment by favoretti** [comment]
Looking at the task spec - you're not using this extension :) 
https://github.com/microsoft/azure-pipelines-extensions/tree/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1

This is the one you've got installed.

**Comment by charleszipp** [comment]
+1 to @favoretti closing this down. @verodhi feel free to re-open if you experience issues with this task when using it in yaml templates.
