### ISSUE TITLE
Service Principal Info Exposed on Terraform Init

### ISSUE THREAD

**Issue by gabrielmccoll** [charleszipp/azure-pipelines-tasks-terraform#174]
When initialising the back end using the AzureRM and a Service Connection to create the items,  the p is not obscured as would be good. 
Hopefully this isn't something dumb I'm doing in the settings!

![charleszipp password backendstep](https://user-images.githubusercontent.com/25871665/100126117-77bf2900-2e75-11eb-8f21-a2b70828edc7.png)

**Comment by charleszipp** [comment]
@gabrielmccoll for the last release i ran on 0.5.16 i am not seeing the client secret in clear text as you are. Can you share your yaml configuration for the init task?
![image](https://user-images.githubusercontent.com/4292559/101181775-e6894880-3612-11eb-8e1d-f1108cebd0e4.png)

**Comment by charleszipp** [comment]
closing as cannot reproduce and issue is stale. can reopen if there are new developments/information on this issue.
