### ISSUE TITLE
Error shows in log when TF Installer has to create Azure storage account for remote state file

### ISSUE THREAD

**Issue by andymcadam** [charleszipp/azure-pipelines-tasks-terraform#184]
**Describe the bug**

When using a new resourcegroup to store teh remote state file, the TerraformCLI command will create the resource group in Azure, then generate an error stating the required storage account does not exist, before then creating the account. This doesn't fail the pipeline but does show as an error, which it shouldn't.

**To Reproduce**

- task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/src/pipelines/scripts/connectManualTestVMs'
          backendType: 'azurerm'
          backendServiceArm: 'DevTest Testing'
          ensureBackend: true
          backendAzureRmResourceGroupName: '${{ variables.resourceGroup }}'
          backendAzureRmResourceGroupLocation: '${{ variables.location }}'
          backendAzureRmStorageAccountName: '${{ variables.saName }}'
          backendAzureRmStorageAccountSku: 'Standard_LRS'
          backendAzureRmContainerName: '${{ variables.containerName }}'
          backendAzureRmKey: 'terraform.tfstate'
          allowTelemetryCollection: true

2. Execute pipeline
3. See error in log when storage account required creating, even though ensureBackend is set to true.

**Expected behavior**
Storage account should be created as the next command after the creation of the resource group, instead it tries to find the storage account, generating the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/6150117/136101832-06c9b643-649d-4fd1-bfd2-946c61fefa49.png)

**Agent Configuration**
 - OS: Windows -latest
 - Hosted
 - Terraform version used:1.0.0
 

**Additional context**

**Comment by jason-johnson** [comment]
The `ensureBackend` flag has now been deprecated so this error will not exist anymore in the release after next.
