### ISSUE TITLE
'forceunlock' command no longer works

### ISSUE THREAD

**Issue by zanawar** [charleszipp/azure-pipelines-tasks-terraform#189]
A defect seems to be have been introduced in the latest version and the `forceunlock` command no longer works like it used to, instead a `Error: Support for command "forceunlock" is not implemented` error is thrown.

Using both `forceUnlock` and `forceunlock` cause this issue.

**Comment by charleszipp** [comment]
In the previous version there was a condition that was hard coded to the `force-unlock` command only where it would rename a command with name `forceunlock` to `force-unlock`. This was in one of the abstractions so it was missed in the refactor. Additionally. there was a misunderstanding about whether `tasks.getInput("command")` would return the key or value from the hash in `task.json`. The updated version was expecting the value to be returned but, its in fact the key. Therefore the mapping for that to a handler had to be updated as well.

Will include with 0.6.5 release.

**Comment by charleszipp** [comment]
released with 0.6.5
