### ISSUE TITLE
TerraformCLI ensureBackend modifies existing resource group

### ISSUE THREAD

**Issue by philchuang** [charleszipp/azure-pipelines-tasks-terraform#189]
https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/329e64b8b5bf8fbc6f3dc61bbec8bd1ce3271d71/tasks/terraform-cli/src/commands/az-group-create.ts#L12

This line is executing ` az group create --name <groupName> --location <location> ` - the problem is, if the resource group already exists, then parts of it get modified. In my experience, it's the tags, but there could be other properties being changed too.

My organization has policies based on resource group tags, so any changes to them break a lot of processes, and it took a bit to hunt down that the cause was a pipeline running the TerraformCLI task with `ensureBackend` set to true.

I don't know if this is an AZ CLI issue or a TerraformCLI task issue, but either way it needs to be made non-modifying.

Please at least add an `az group exists` check before running `az group create` - in the meantime, we cannot use your helpful extension.

**Comment by jason-johnson** [comment]
@philchuang Is this still an issue?  Would removing `ensureBackend: true` be a workaround?

**Comment by philchuang** [comment]
@jason-johnson unsure, this issue is almost 2 years old, so we've moved onto either manually executing terraform or terragrunt via powershell tasks.

**Comment by jason-johnson** [comment]
Closing this issue.  The recommendation is: `ensureBackend: true` is a convenience function, not really a production feature.  If you have issues with it then the best thing to do is create the storage account outside of the pipeline, or at least with some other task in the pipeline.
