### ISSUE TITLE
Azure Devops Warning

### ISSUE THREAD

**Issue by treyhendon** [charleszipp/azure-pipelines-tasks-terraform#199]
Had a new Azdo warning show up today.  I believe this is task related (not TF itself).

```
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
```

Not sure what impact this will have, but wanted to share just in case it's going to be a problem.

**Comment by charleszipp** [comment]
Since we are well into march and there has been no issues reported related to this, I do not believe any action is necessary at this time. Thanks @treyhendon for reporting this. Will revisit if issues begin to surface around the encoding.
