### ISSUE TITLE
Feature Request: Annotate PullRequest

### ISSUE THREAD

**Issue by jleechpe** [charleszipp/azure-pipelines-tasks-terraform#201]
Would it be possible to do something similar to what SonarQube does and publish a Status Check for Plan Results along with the warnings/plan view (especially to monitor for Deletions)?

Ideally also allowing the Plan to be added as a comment in the relevant PR for simpler review of the changes.

**Comment by jason-johnson** [comment]
Hi @jleechpe, could you provide a link to something that describes the functionality you mean?  I'm not familiar enough with SonarQube I'm afraid.

**Comment by jason-johnson** [comment]
Nothing heard on this for over a year.  Closing.  If there is still interest, please re-open and comment on it.
