### ISSUE TITLE
Enabling the ensureBackend flag to create storage account not working

### ISSUE THREAD

**Issue by sheikahamedali** [charleszipp/azure-pipelines-tasks-terraform#207]
**Describe the bug**
In order to create the storage account , blob container and the terraform state file key as part of the terraform Init task, I enabled the flag "ensureBackend" to true and provided the following parameters

        command: init
        backendType: azurerm
        backendServiceArm: 'My Azure Service Connection'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'my-backend-resource-group'
        # azure location shortname of the backend resource group and storage account
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'my-backend-storage-account'
        # azure storage account sku, used when creating the storage account
        backendAzureRmStorageAccountSku: 'Standard_RAGRS'
        # azure blob container to store the state file
        backendAzureRmContainerName: 'my-backend-blob-container'
        # azure blob file name
        backendAzureRmKey: infrax.tfstate

The execution of this task thrown the following error 

ERROR: az: error: unrecognized arguments: --allow-blob-public-access false --min-tls-version TLS1_2
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {storage} ...

##[debug]Exit code 2 received from tool '/usr/bin/az'
##[debug]STDIO streams have closed for tool '/usr/bin/az'
##[debug]allowTelemetryCollection=true
##[error]Error: ERROR: az: error: unrecognized arguments: --allow-blob-public-access false --min-tls-version TLS1_2

**Comment by charleszipp** [comment]
@sheikahamedali can you please provide the entire build log when init is run? I need to be able to see the command being issued to the azure cli which should be visible in the build log. Please redact any sensitive info such as resource names, subscription ids, tenant ids, etc.

**Comment by sheikahamedali** [comment]
@charleszipp  Thank you for looking into this issue. Here are the logs.


az storage account create: storage account not found, creating...
##[debug]backendAzureRmStorageAccountName=apimpr01prodstate
##[debug]backendAzureRmResourceGroupName=apim-pr01-prod-rg
##[debug]backendAzureRmStorageAccountSku=Standard_LRS
##[debug]which 'az'
##[debug]found: '/usr/bin/az'
##[debug]which '/usr/bin/az'
##[debug]found: '/usr/bin/az'
##[debug]/usr/bin/az arg: storage
##[debug]/usr/bin/az arg: account
##[debug]/usr/bin/az arg: create
##[debug]/usr/bin/az arg: --name
##[debug]/usr/bin/az arg: apimpr01prodstate
##[debug]/usr/bin/az arg: --resource-group
##[debug]/usr/bin/az arg: apim-pr01-prod-rg
##[debug]/usr/bin/az arg: --sku
##[debug]/usr/bin/az arg: Standard_LRS
##[debug]/usr/bin/az arg: --kind
##[debug]/usr/bin/az arg: StorageV2
##[debug]/usr/bin/az arg: --encryption-services
##[debug]/usr/bin/az arg: blob
##[debug]/usr/bin/az arg: --access-tier
##[debug]/usr/bin/az arg: hot
##[debug]/usr/bin/az arg: --allow-blob-public-access
##[debug]/usr/bin/az arg: false
##[debug]/usr/bin/az arg: --https-only
##[debug]/usr/bin/az arg: true
##[debug]/usr/bin/az arg: --min-tls-version
##[debug]/usr/bin/az arg: TLS1_2
##[debug]exec tool: /usr/bin/az
##[debug]arguments:
##[debug]   storage
##[debug]   account
##[debug]   create
##[debug]   --name
##[debug]   apimpr01prodstate
##[debug]   --resource-group
##[debug]   apim-pr01-prod-rg
##[debug]   --sku
##[debug]   Standard_LRS
##[debug]   --kind
##[debug]   StorageV2
##[debug]   --encryption-services
##[debug]   blob
##[debug]   --access-tier
##[debug]   hot
##[debug]   --allow-blob-public-access
##[debug]   false
##[debug]   --https-only
##[debug]   true
##[debug]   --min-tls-version
##[debug]   TLS1_2
/usr/bin/az storage account create --name apimpr01prodstate --resource-group apim-pr01-prod-rg --sku Standard_LRS --kind StorageV2 --encryption-services blob --access-tier hot --allow-blob-public-access false --https-only true --min-tls-version TLS1_2
ERROR: az: error: unrecognized arguments: --allow-blob-public-access false --min-tls-version TLS1_2
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {storage} ...

##[debug]Exit code 2 received from tool '/usr/bin/az'
##[debug]STDIO streams have closed for tool '/usr/bin/az'
##[debug]allowTelemetryCollection=true
##[error]Error: ERROR: az: error: unrecognized arguments: --allow-blob-public-access false --min-tls-version TLS1_2

usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {storage} ...

**Comment by charleszipp** [comment]
@sheikahamedali is the agent being used hosted or self hosted? If hosted, what OS/sku? Lastly, can add a step to run `az -v` to verify what version of the cli is being used?

**Comment by sheikahamedali** [comment]
The pipeline is running on a self-hosted azure agent with  agent version: '2.193.1'; OS - Linux. 

Here is the CLI version used - azure-cli (2.0.54); Terraform version used is 1.0.9 and the provider version used is "~> 2.72.0".

Please let me know if you need any additional details. Thanks again.

**Comment by charleszipp** [comment]
The issue is due to your azure cli being out of date. The latest is 2.29.0 so it seems what you are currently using is very out of date. Please upgrade the cli and that should resolve the issue. The link below shows these args are supported in the current version of the azure cli
https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az_storage_account_create

**Comment by sheikahamedali** [comment]
Ah. Thank you for pointing out the issue. I will try upgrading the CLI version and try again.
