### ISSUE TITLE
On Demand Feature Branch Environments

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#21]
# User Story
As an engineer, I would like to provision a new environment for my feature branch so that I can save money by only paying for environments I am actively using and test features in environments isolated from other engineers.

_This would also allow for on-demand and automated provisioning and tear down of environments for automation/integration testing._

### Workspace per Feature Branch
In this strategy, a workspace would be created per feature branch 1:1. The resources provisioned would need to include the branch name to ensure uniqueness. 
#### Depends On
#19 for automated provisioning of remote backends
#20 for integration with workspaces. Workspaces would be needed to have separate state per feature branch.
#22 for removing creating workspace environments. Without this, there would be no easy way to tear down the created workspace from azure devops. (it would need to be done with batch or shell script)

**Comment by ChethanRavulaGit** [comment]
Hi Charles
Is there a possibility to run workspace commands using the terraform CLI tasks?
If not what is your suggestion to create workspace and work with workspace still using the terraform tasks?

**Comment by charleszipp** [comment]
> Hi Charles
> Is there a possibility to run workspace commands using the terraform CLI tasks?
> If not what is your suggestion to create workspace and work with workspace still using the terraform tasks?

Hey @ChethanRavulaGit. This is not possible at this time. This is planned as part of #20. The closest you could probably get is to simulate workspaces by dynamically setting the container or blob name of the state (i.e. setting it to pipeline variable). However, it is not possible to run the workspace command directly using the CLI task. 

It would help to prioritize #20 if you could add (here or within issue #20) how you intend to use the workspace command with the CLI task. This current issue has its own opinions about how/why you may use it but, i would be interested to know if there are other use cases I havent considered.

Appreciate the inquiry and look forward to the feedback!

**Comment by ChethanRavulaGit** [comment]
@charleszipp 
While using the backend provided on the Terraform int; is there any way to also select existing Blob within Container?
For Destroy task, is there a possible way to select existing workspace Blob?
#20 is closed.

**Comment by charleszipp** [comment]
@ChethanRavulaGit I believe you could do this just by ensuring the backend inputs line up to the name of the existing storage account, container, and blob file. Can you try this and let me know if that does not work if you havent already?

You may be able to run a bash command using azure cli task that switches the workspace. Then run destroy with the tf command task after. So do somehting like this...

1. TF Init
2. Azure CLI task runs a bash script to switch workspaces
3. TF Destroy

**Comment by ChethanRavulaGit** [comment]
@charleszipp; i am able to provide Storage, Container name but no field to pass the Blob name; Where are you suggesting to provide the Blob name? 

Can you share the bash script to switch workspaces?

Thank you for such prompt response

**Comment by charleszipp** [comment]
@ChethanRavulaGit 

**Key** = Blob name

in the image below, my state is written to a blob file named vs2017.tfstate

![image](https://user-images.githubusercontent.com/4292559/58044928-ae8ce400-7b06-11e9-8917-b710f99e10a2.png)
![image](https://user-images.githubusercontent.com/4292559/58045062-04fa2280-7b07-11e9-9950-4f463b904a30.png)

**Comment by ChethanRavulaGit** [comment]
Thanks @charleszipp 
I was inputting the Storage account Key in the Key field. putting the Blob name worked for me.

But i got into another issue; My blob files are as below
![image](https://user-images.githubusercontent.com/23094793/58184719-41e52700-7c77-11e9-929c-1da831656e63.png)

so on Key field i am using "rise2-terraform.tfstateenv:$(Environment)" so it finds the right Blob. When i look at the Terraform INT log..its clear that the right Blob i selected
-backend-config=key=rise2-terraform.tfstateenv:CIN
When the planb is executed the resources are create with default env.. which is the default Blob without any Env on it.
Any help on how to get around this?

**Comment by charleszipp** [comment]
Closing stale issue, will revisit this after workspace support is added
