### ISSUE TITLE
Output not writing to ADO pipeline variables

### ISSUE THREAD

**Issue by JFolberth** [charleszipp/azure-pipelines-tasks-terraform#214]
**Describe the bug**
Using an output from a module to hopefully write an ADO TF variable. When running locally am able to see the output from my Terraform via CLI; however, ADO does not recognize it.

Followed documentation and also ran:
`           - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'env | sort'
`
The result does not show the output as a variable.

**To Reproduce**
YAML:
`steps:
    - task: TerraformCLI@0
      displayName: 'terraform output'
      inputs:
        command: output`

Terraform:
`output "resource_group_name" {
    sensitive = false
    value = module.infrastructure.resource_group_name
}`
**Expected behavior**
Would expect the out put defined in my Terraform to be available to the ADO agent.

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: ubuntu
 - Hosted
 - Terraform version used 0.15.3
 - AzureCLI version used Default for hosted agent

**Comment by charleszipp** [comment]
@JFolberth, can you send me the portion of your pipeline yaml and the log output from the terraform output task? Couple things you can also check in the mean time
1. There is an example pipeline that runs output [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/1820d870f81ef1ce74a8e18dec417fb2604b1843/pipelines/test/smoke_test.yml#L55)
2. Make sure the working directory on the output step is set to the same working directory as other instances of the task (i.e. plan and/or apply)
3. Try the bash step [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/1820d870f81ef1ce74a8e18dec417fb2604b1843/pipelines/test/smoke_test.yml#L60) to check if the pipeline variables are available.

**Comment by agsonsmith** [comment]
I had the same problem, but once I added the working directory to the terraform output task my variables were available in the pipeline.  I was following the plugin documentation for this and it doesn't note that the working directory on the output step is set to the same working directory as other instances of the task.

Would you mind updating the plugin doco to include that specifically in the "Terraform Output to Pipeline Variables" section?  Would help the next set of people using it to avoid the same mistake I made.

**Comment by charleszipp** [comment]
Thanks for the feedback @agsonsmith. I have created #221 to update the docs.

**Comment by ASalihov** [comment]
> **Describe the bug** Using an output from a module to hopefully write an ADO TF variable. When running locally am able to see the output from my Terraform via CLI; however, ADO does not recognize it.
> 
> Followed documentation and also ran: ` - task: Bash@3 inputs: targetType: 'inline' script: 'env | sort'` The result does not show the output as a variable.
> 
> **To Reproduce** Steps to reproduce the behavior: YAML: `steps: - task: TerraformCLI@0 displayName: 'terraform output' inputs: command: output`
> 
> Terraform: `output "resource_group_name" { sensitive = false value = module.infrastructure.resource_group_name }` **Expected behavior** Would expect the out put defined in my Terraform to be available to the ADO agent.
> 
> **Pipeline Logs** Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.
> 
> **Agent Configuration**
> 
> * OS: ubuntu
> * Hosted
> * Terraform version used 0.15.3
> * AzureCLI version used Default for hosted agent

Hello!
Did you find solution?
Still doesn't work for me even with working directory specified.
