### ISSUE TITLE
Support Destroy Commands

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#22]
As an engineer, I would like the ability to tear down my environment, so that I do not pay for resources I am not actively using.

**Comment by jakebair** [comment]
howdy, I'm currently working on this... I'll have a PR soon for your review

**Comment by charleszipp** [comment]
Thanks @jakebair! Your contribution will be much appreciated!

**Comment by charleszipp** [comment]
deployed with 0.3.3. There will be a quick follow up release 0.3.4 which includes doc updates to overview. Waiting to close until that is pushed through

**Comment by charleszipp** [comment]
Merged and released doc updates with 0.3.4. Big thanks to @jakebair for your contribution. This will be much appreciated by the community!
