### ISSUE TITLE
allowTelemetryCollection

### ISSUE THREAD

**Issue by rdelgado-incomm** [charleszipp/azure-pipelines-tasks-terraform#223]
What is `allowTelemetryCollection` used for?

**Comment by charleszipp** [comment]
In case anyone comes across this issue, this input can be used to disable telemetry collection. Telemetry collection is enabled by default. 

The telemetry is anonymized usage data that helps provide insight into 
1) what features of the task are being used
2) how frequently are features being used
3) how frequently are they failing

All this helps drive decisions about where contributors should invest time.

Setting `allowTelemetryCollection: false` will prevent this data from being collected.
