### ISSUE TITLE
Secure File - referenced by GUID instead of name

### ISSUE THREAD

**Issue by AIPeterKyrannis** [charleszipp/azure-pipelines-tasks-terraform#225]
**Describe the bug**
In the terraform plan/apply commands where a secured variable file is used, the reference is to the guid of the file instead of the name. This means that if you delete the secure file and upload a new version, you have to go into each pipeline and update the file from the drop down again. Could it be referenced by name or can a selectable option be added to do that? The name is as unique as the guid because Azure DevOps doesn't let you upload two files with the same name

**To Reproduce**
1. YAML
steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform plan'
  inputs:
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: '***'
    secureVarsFile: 'dea83356-8fd8-4315-9ede-e440fd6e05a2'
    commandOptions: '-no-color'
    allowTelemetryCollection: false
2. Delete and upload a new version of the secure file (pipeline > library > secure files)
3. The pipeline will error unless you go into each pipeline and select the new secure file (with the same name)

**Expected behavior**
When you upload a new version of the secure file, the pipeline task does not need amending

**Agent Configuration**
 - OS: ubuntu-20.04
 - Hosted
 - Terraform version used: default
 - AzureCLI version used: default

**Comment by charleszipp** [comment]
@AIPeterKyrannis you should be able to use the name. I have tested this while working on the AWS integration. The sample pipelines I have created for the aws integration all use the file name rather than the guid. See [this example](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/601b8e966cb059410033b45329f89215ada3e1cf/pipelines/test/aws_self_configured.yml#L28)

Feel free to reopen if you are still unable to use the file name

**Comment by AIPeterKyrannis** [comment]
Hi @charleszipp ,
Thanks for coming back so promptly.
I should have mentioned, that i'm using an Azure classic pipeline and select the file > click save. When I view the yaml at this point, it shows the name.
![image](https://user-images.githubusercontent.com/83447746/144621160-fa357aa1-6612-438c-9b56-b86784817323.png)
but when I delete the secure file in the library and replace it with a new version (of the same name). I go back into the pipeline and find that the variable field is blank and the yaml displays the guid of the old secure file I deleted.
