### ISSUE TITLE
Secure File - referenced by GUID instead of name

### ISSUE THREAD

**Issue by AIPeterKyrannis** [charleszipp/azure-pipelines-tasks-terraform#228]
Hi @charleszipp ,
Thanks for coming back so promptly.
I should have mentioned, that i'm using an Azure classic pipeline and select the file > click save. When I view the yaml at this point, it shows the name.
![image](https://user-images.githubusercontent.com/83447746/144621160-fa357aa1-6612-438c-9b56-b86784817323.png)
but when I delete the secure file in the library and replace it with a new version (of the same name). I go back into the pipeline and find that the variable field is blank and the yaml displays the guid of the old secure file I deleted.

_Originally posted by @AIPeterKyrannis in https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/225#issuecomment-985576208_

**Comment by jason-johnson** [comment]
Hi @AIPeterKyrannis , are you still having this issue?  It seems like it's got something to do with how classic pipelines handle secure files and not this extension?

**Comment by jason-johnson** [comment]
No response in a month.  Closing.  Feel free to reopen if the issue persists.
