### ISSUE TITLE
Does this task support authenticating azure service principal using a certificate

### ISSUE THREAD

**Issue by smushtaq** [charleszipp/azure-pipelines-tasks-terraform#235]
I am trying to use this task to deploy my terraform infrastructure to azure using a certificate enabled service principal. Everytime i run the terraform init it runs this command using the clientid and client secret which is undefined.

`[command]/opt/hostedtoolcache/terraform/0.14.5/x64/terraform init -backend-config=storage_account_name=*** -backend-config=container_name=*** -backend-config=key=terraform.tfstate -backend-config=resource_group_name=*** -backend-config=arm_subscription_id=*** -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=undefined`

instead i want it to use 

`[command]/opt/hostedtoolcache/terraform/0.14.5/x64/terraform init -backend-config=storage_account_name=*** -backend-config=container_name=*** -backend-config=key=terraform.tfstate -backend-config=resource_group_name=*** -backend-config=arm_subscription_id=*** -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_certificate_path=***  -backend-config=arm_client_certificate_password=***`

as described on this link. 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate

Any ideas how i can achieve this using this task.

**Comment by charleszipp** [comment]
The task currently only supports the service principals that use client_id and secret. You could however, set the backend-type to `self-configured`. Then using a secure var file or, or your own command options, provide the configuration values. There is an example of how to do a self-configured backend using a secure file in one of the e2e tests [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/pipelines/test/init_with_self_configured_backend.yml)

**Comment by smushtaq** [comment]
Thanks. yea. self-configured option worked for me. Thanks for providing the example test pipeline.

**Comment by charleszipp** [comment]
@smushtaq this is a requirement of terraform itself, not this task. Configuration must be provided for each provider and backend when running terraform. It may be easier to provide that config via a terraform vars file. You can do this with the task by uploading a vars file to azure devops in pipelines > library > secure files. This vars can contain the config for both the backend and provider. Most backends and providers in terraform support config via environment vars.

``shell
spn_client_certificate_password=password
spn_client_certificate_path=/path/to/cert
tenant_id=my-tenant-id
subscription_id=my-sub-id
spn_object_id=my-client-id
backend_resource_group=my-resource-group
backend_storage_account_name=my-storage-account-name
backend_container_name=my-container-name
backend_key=my-blob-file-name
```

Then in your terraform files you could do the following

```terraform
terraform {
  backend "azurerm" {
       resource_group_name         = var.backend_resource_group
       storage_account_name        = var.backend_storage_account_name
       container_name              = var.backend_container_name
       key                         = var.backend_key
       client_id                   =  var.spn_object_id
       client_certificate_password = var.spn_client_certificate_password
       client_certificate_path     = var.spn_client_certificate_path
       subscription_id             = var.subscription_id
       tenant_id                   = var.tenant_id
    }
}
```

The provider terraform configuration can remain as you defined in the provided example

**Comment by smushtaq** [comment]
Thanks. I am generating the top backend file as part of the release pipeline and not including in the terraform repo so that i can use a local backend when running it locally. But anywayz, looks like i have to configure both the backend and the provider in any case. But thanks for the help. I will close this question now.
