### ISSUE TITLE
Error: Input required: backendAzureRmStorageAccountSku

### ISSUE THREAD

**Issue by datapanda99** [charleszipp/azure-pipelines-tasks-terraform#238]
Basically identical to #235 but now with the parameter `backendAzureRmStorageAccountSku`.

Previously, this parameter wasn't required and we didn't use it, but now it appears to be required.
Yesterday, we already had the same issue with `backendAzureRmResourceGroupLocation`.

**Comment by charleszipp** [comment]
This should be fixed with 0.7.2 @datapanda99. Please confirm when possible

**Comment by datapanda99** [comment]
@charleszipp Yes, it's working es expected again. Thank's for the quick fix!
