### ISSUE TITLE
Error: Input required: backendAzureRmResourceGroupName since 0.7.1

### ISSUE THREAD

**Issue by rhollins** [charleszipp/azure-pipelines-tasks-terraform#239]
I can see following error since update on 29 Dec to 0.7.1

Error: Input required: backendAzureRmResourceGroupName

azure provider: 2.74.0
terraform: 0.12.31

Also the way we use this extension hasn't changed at all same as TF version and azure provider version

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: "Terraform Init - ${{ parameters.ENV }}"
    inputs:
      command: init
      backendType: azurerm
      workingDirectory: '${{ parameters.WORK_DIR }}'
      backendServiceArm: ${{ parameters.STATE_SC }}
      backendAzureRmResourceGroupName: ${{ parameters.STATE_SA_RG_NAME }}
      backendAzureRmStorageAccountName: ${{ parameters.STATE_SA_NAME }}
      backendAzureRmContainerName: ${{ parameters.STATE_CONTAINER_NAME }}
      backendAzureRmKey: ${{ parameters.STATE_BACKEND_KEY }}

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: "Terraform Plan - ${{ parameters.ENV }}"
    inputs:
      command: plan
      backendType: azurerm
      workingDirectory: '${{ parameters.WORK_DIR }}'
      commandOptions: '-out=tfplan
                      ${{ parameters.COMMAND_PARAMS }}'
      environmentServiceName: ${{ parameters.SC }}

Also the last successful run was on 2021-12-29T00:03:11 - worked fine and then it failed on 2021-12-30T00:03:05 - didn't worked

**Comment by charleszipp** [comment]
@rhollins can you confirm there is a value being provided to resource group param? This has always been required even before 0.7.1 was released. It does look similar to #239 and #235. However, if I revert to before 0.7.0 & 0.7.1, I can only reproduce this if there is no value provided to `backendAzureRmResourceGroupName`.

**Comment by charleszipp** [comment]
@rhollins I am including #15 as part of the next round of updates as it should prevent any more of these input required issues. That should also resolve the issue for resource group name. However, I fear that because resource group has always been required regardless of whether ensureBackend is enabled there may be something else going on with the pipeline. This was part of why #15 was requested as they want to be able to define these values elsewhere without the task requiring them be in the tasks inputs.

**Comment by rhollins** [comment]
Thanks for a quick update, it works now with the same parameters as provided in the issue, both of those tasks run within the same job. By the way Happy New Year :) !
