### ISSUE TITLE
Terraform plan view fails to display plan summary

### ISSUE THREAD

**Issue by alex-goncharov** [charleszipp/azure-pipelines-tasks-terraform#245]
The error is as if the view is not configured
`No terraform plans have been published for this pipeline run. The terraform cli task must run plan with publishPlanResults: string (where string represents the plan name) to view plans.`

But the debug output shows otherwise:

`
variable=TERRAFORM_PLAN_HAS_CHANGES;isOutput=false;issecret=false;]true 
##[debug]publishPlanResults=terraform__plan 
##[debug]publishPlanResults=terraform__plan 
##[debug]publishPlanResults=terraform__plan 
##[debug]workingDirectory=/azp/agent/_work/1/s/ 
##[debug]publishPlanResults=terraform__plan 
##[debug]Absolute path for pathSegments: /azp/agent/_work/1/s/,terraform__plan = /azp/agent/_work/1/s/terraform__plan 
##[debug]Processed: ##vso[task.addattachment type=terraform-plan-results;name=terraform__plan;]/azp/agent/_work/1/s/terraform__plan
`

The web console reveals the actual problem:
`
Fetch.js:118 GET https://dev.azure.com/our-org-name/our-org-name/_apis/build/builds/49762/a9e909ca-90cd-4619-a148-190899578af8/41273665-1000-5ced-ace3-bbb41da53d4e/attachments/terraform-plan-results/terraform_nonprod_plan 400
...
azdo-attachment-service.ts:105 Uncaught (in promise) Error: Failed to download plain plan: TFS.WebApi.Exception: TF200016: The following project does not exist: our-org-name. Verify that the name of the project is correct and that the project exists on the specified Azure DevOps Server.
    at t.default.<anonymous> (azdo-attachment-service.ts:105)
`

it looks like 
`https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/f689a7a74d14c6c71dc74d2a3d6dc6589664cc5d/views/terraform-plan/src/services/attachments/azdo-attachment-service.ts#L89`

should use second segment 2 (i assume  pathname to be /org-name/project-name) instead of 1, because split('/') should produce ["", "org-name", "project-name", ...]

**Comment by charleszipp** [comment]
Thanks for taking care of this @favoretti and @alex-goncharov! I think this was missed because in the org/project where I was testing this, the org and project names are the same.  I am going to quickly verify I can still see plans from latest on master then will publish to marketplace.

**Comment by charleszipp** [comment]
The fix for this has been released with 0.6.13
