### ISSUE TITLE
azure keyvault secret output is sometimes, and sometimes not, redacted

### ISSUE THREAD

**Issue by scott-doyland-burrows** [charleszipp/azure-pipelines-tasks-terraform#250]
Hi,

Is the output from the keyvault always supposed to be redacted.  I am seeing a few odd things where sometimes secrets are redacted, and sometimes not:

I have this defined:

```
data "azurerm_key_vault_secret" "secret" {
  name         = "mysecret"
  key_vault_id = data.azurerm_key_vault.keyvault.id
}

output "secret" {
  value = data.azurerm_key_vault_secret.secret.value
}



data "azurerm_key_vault_secret" "secret2" {
  name         = "mysecret2"
  key_vault_id = data.azurerm_key_vault.keyvault.id
}

output "secret2" {
  value = data.azurerm_key_vault_secret.secret2.value
}

```

Running this locally (not via the pipeline), I always see the secrets, so I do not think terraform itself redacts them.

Through the pipleline I see this on the plan stage.
The value of ```secret``` is actually ```abcdef```
The value of ```secret2``` is an Azure service principal password. 

```
2021-03-10T13:16:12.3662947Z Changes to Outputs:
2021-03-10T13:16:12.3663273Z   + secret                               = "abcdef"
2021-03-10T13:16:12.3664558Z   + secret2                              = ***

**Comment by charleszipp** [comment]
@scott-doyland-burrows as @alex-goncharov mentioned, this looks like ADO automatically determining some values are sensitive. To protect from this I would recommend to set the output variable as a sensitive value explicitly. This will ensure terraform redacts the value no matter where its runs (i.e. ADO, locally, etc).

This task is not responsible for determining what values are sensitive and redacting them. That should be indicated via configuration in the terraform template.

ADO itself (not this task) will also redact pipeline variables that are marked as secrets from the build log

**Comment by charleszipp** [comment]
Closing since this is appears to be ADO and/or Terraform configuration related issue.

**Comment by scott-doyland-burrows** [comment]
Thanks for the reply.  

I can see that some values get marked:

```"***"``` I think this is terraform setting it as sensitive
and some
```***``` which as you say, must be ADO setting as sensitive

From some more testing, based on your reply, it looks like ADO will mark strings such as Azure service principals UIDs and service principal passwords as sensitive (and maybe other strings as well).  I tried a random long sting and it was still shown in full in ADO - as ADO didn't recognise it as needing to be a sensitive string.

**Comment by charleszipp** [comment]
@scott-doyland-burrows ill see if I can hunt down some docs that provide a more complete explanation of how this works. If I find one I will post that here.
