### ISSUE TITLE
Warnings in pipeline for 0.6.14 release

### ISSUE THREAD

**Issue by scott-doyland-burrows** [charleszipp/azure-pipelines-tasks-terraform#252]
Hi,

I know this isn't a bug per se, but working as designed.

With the 0.6.14 release it produces a warning in the ADO logs if there are plan changes - which makes it looks like the pipeline is not working as expected.  

But it is working as expected.  I want it to make changes, that's the reason for running the pipeline.

I now have to always check the pipeline to ensure there are not any "real" warnings.

```
2021-03-12T08:58:15.4739915Z ##[warning]Plan 'false' is going to create 1 resources.
2021-03-12T08:58:15.4753552Z ##[warning]Plan 'false' is going to update 1 resources.
2021-03-12T08:58:15.4755489Z ##[warning]Plan 'false' is going to destroy 1 resources.
```

Note it says ```false``` in the messages, I assume that is because I am not actually writing to a plan file.

I am running "classic" pipelines, I did see something regarding ```publishPlanResults``` and I think maybe I can switch off the new warning feature, but I cannot see where I would set/unset this.

**Comment by alex-goncharov** [comment]
Hi,

The `publishPlanResults` parameter is used as a name for the attachment, which is then pulled by UI to present you a short summary of the plan. Unset this parameter to disable publishing, which will also disable the warnings.

**Comment by scott-doyland-burrows** [comment]
Hi,

Ah, I just checked the ```plan``` task and it has ```publishPlanResults``` set to ```false```.

How this got set to ```false``` I do not know.

Thanks very much for pointing me in the right direction.

**Comment by charleszipp** [comment]
To add more explanation to this, the `publishPlanResults` input was originally boolean/checkbox type in earlier releases. So for those using classic UI, this may have gotten set to false. In the latest versions its a string that indicates the name. For anyone else experiencing this issue, just make sure the publish plan results field is cleared out.

Closing this as it seems there is a pretty simple fix that does not require a code change.
