### ISSUE TITLE
Azure DevOps Release Pipeline task terraform state remove : Error: Input required: stateSubCommandAddresses

### ISSUE THREAD

**Issue by emmanuelsomeox** [charleszipp/azure-pipelines-tasks-terraform#259]
**Describe the bug**
Error Input required: stateSubCommandAddresses when running a Classic task for terraform state remove
Set variable in field "State list and rm addresses) 

**To Reproduce**
1. Setup pipeline as
 
![image](https://user-images.githubusercontent.com/65308853/157780982-3941f339-bcd8-4a5f-a316-9f8ab35996b6.png)
YAML file displayed :
![image](https://user-images.githubusercontent.com/65308853/157781180-b4072852-b6fd-4f6d-a07b-1c8e6373af5d.png)

2. Execute pipeline
3. See error
Get error "[error]Error: Input required: stateSubCommandAddresses" at execution of the task

**Expected behavior**
Variable stateSubCommandAddresses should be passed instead of stateAddresses

**Agent Configuration**
 - OS: Windows 2022
 - Hosted
 - Terraform version used (Default) 
 - AzureCLI version used (Default)

**Comment by Amal50** [comment]
I have same issue using agent ubuntu-latest
