### ISSUE TITLE
Workspace Sub Command is required even without using "workspace" command

### ISSUE THREAD

**Issue by anthturner** [charleszipp/azure-pipelines-tasks-terraform#264]
**Describe the bug**
When using classic editor/release editor, the "Workspace Sub Command" is now required, even when using commands like "init" or "plan"

**To Reproduce**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/225599/114587199-6bd0d980-9c53-11eb-988f-9429f624850d.png)

**Expected behavior**
This breaks existing pipelines -- this setting should be made optional when not using "workspace"

**Comment by charleszipp** [comment]
FYI for others that may be experiencing this issue. This is being investigated. Will post more updates here as they are available.

**Comment by charleszipp** [comment]
After much testing it appears setting the visible rule resolves this issue for the classic UI pipelines. PR #265 will resolve this.

**Comment by pjeannet** [comment]
Do you know when this will be released? We currently can't fix the plugin version (at least in classic UI, see bellow) and this change is kinda blocking us as we can't edit the pipelines anymore.
To prevent these kind of breaking bugs, can something be done to allow us to choose the plugin version from the UI? 
![image](https://user-images.githubusercontent.com/6052793/114691138-a3a15500-9d17-11eb-887e-b6a9f2067d22.png)

Thanks

**Comment by charleszipp** [comment]
This should be released within the next few hours with the release of 0.6.18.

**Comment by charleszipp** [comment]
0.6.18 is now available which fixes this issue
