### ISSUE TITLE
Command options field disappeared after latest update

### ISSUE THREAD

**Issue by pjeannet** [charleszipp/azure-pipelines-tasks-terraform#266]
**Describe the bug**
After yesterday and today updates, the field for command options disappeared from the classic UI. Thus when in selg-configured mode we can't pass `-backend-config` options to the init command.

**To Reproduce**
1. Setup pipeline as in classic UI with init task
2. Can't set command options

**Expected behavior**
A field should exist to pass command options to tasks in classic UI

**Screenshots**
![image](https://user-images.githubusercontent.com/6052793/114719195-1f5eca00-9d37-11eb-9990-15ce78fbd422.png)

**Comment by charleszipp** [comment]
Fix is available now with 0.6.19
