### ISSUE TITLE
Allow users to override url used to install terraform

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#27]
As an enginer, I would like to be able to provide the full download path for the terraform executable, so that I can ensure terraform is installed from my company's approved location

**Comment by favoretti** [comment]
@charleszipp if you're ok with #126 I can then hack this on top. I have this feeling we'll need it soon as well.

**Comment by charleszipp** [comment]
> @charleszipp if you're ok with #126 I can then hack this on top. I have this feeling we'll need it soon as well.

Absolutely! #126 is fairly small so I am good with that.

**Comment by charleszipp** [comment]
Will be fixed with 0.5.8
