### ISSUE TITLE
Terraform Plan View usage

### ISSUE THREAD

**Issue by FernandoMiguel** [charleszipp/azure-pipelines-tasks-terraform#270]
Due to some specific implementation reasons, we couldn't use this extension directly, and had to use AzureCLI tasks for init/plan/apply.

But we would still like to us the Terraform Plan View feature to create a view in AzDO summary section. 

Are there any releases of this feature we can use in the pipeline to consume a plan output ?

thanks in advance

**Comment by charleszipp** [comment]
Hi @FernandoMiguel, there are not any releases currently or planned that would allow the plan view to be usable without the terraform cli task. If you wanted to use the terraform plan view only, you would need to push the stdout from terraform plan as a build attachment. You can see how this is done in the [tf-plan.ts](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/a59d29f61cf99bee0962e63794ae709145f1ce28/tasks/terraform-cli/src/commands/tf-plan.ts#L64) file. If you are able to publish and attachment with the same type as what is in the tf-plan.ts, then the plan view should be able to retrieve it. Unfortunately, I am not familiar with how this would be done outside of the node sdk. Maybe there is an attachment extension out there that would allow publish a file you generate from the pipeline?

**Comment by FernandoMiguel** [comment]
there are things like https://github.com/microsoft/vsts-extension-samples/tree/master/build-results-enhancer
and https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results

but many moving parts.
if any of this could either produce a "test" like result, then we could use AzDO own task to push it there

**Comment by FernandoMiguel** [comment]
Anyway, after tinkering with this task a bit I got it to work for one of our pipelines.
May need to test it more.
Having an example of how to use env would be pretty nice for anyone new to the project.
