### ISSUE TITLE
Azure Release Pipeline failed to install terraform 0.14.0 with exception "Error: certificate has expired" 

### ISSUE THREAD

**Issue by yoshuhire** [charleszipp/azure-pipelines-tasks-terraform#272]
When I executed one of azure release pipeline task "Terraform Installer 0.14.0", it failed with an error "cerfiticate has expired".

Terraform Install version 0.14.0

Task         : Terraform Installer
Version      : 0.6.8
Author       : Charles Zipp

the task was running fine until 2022/5/25 JST.

Could you please tell me what and how I fix to resolve the issue?

Azure Pipeline Agent's Configuration is as below.

OS: Ubuntu latest (ubuntu-22.04)
Agent Type: Microsoft Hosted Agent

**Comment by waarg** [comment]
Same issue here

**Comment by waarg** [comment]
We fixed this in organization settings. Under extensions, we had to give permission to upgrade the terraform installer task. Then on next run, it ran v0.7.8 of the task and it worked - the cert error did not recur.

**Comment by yoshuhire** [comment]
Thank you so much!
I'll try n get right back!

**Comment by jason-johnson** [comment]
@yoshuhire Did this fix your issue or is there a potential bug here?

**Comment by yoshuhire** [comment]
Forgive my late response.
Yes! This issue has been resolved after upgrading the terraform task!
Thank you!

**Comment by jason-johnson** [comment]
Great, thanks.  In that case, closing the issue.
