### ISSUE TITLE
Support for command Force-unlock" is not implemented

### ISSUE THREAD

**Issue by maddingo** [charleszipp/azure-pipelines-tasks-terraform#274]
The documetnation states that force-unlock is supported. When running version 0.7.8 I get the following error:
##[error]Error: Support for command "force-unlock" is not implemented

**Comment by oloktyev** [comment]
I guess the actuall command is 'forceunlock' and not 'force-unlock'. Here is an example how to use it:

- task: TerraformCLI@0
      displayName: 'Run terraform force-unlock'
      inputs:
        command: forceunlock
        lockID: 'b32e34a4-5cdc-7832-7e6e-926005ccad65'

**Comment by maddingo** [comment]
Thanks @oloktyev. Then I guess the documentation has to be updated.

**Comment by jason-johnson** [comment]
Will merge the PR as soon as I have everything set up from the project transfer
