### ISSUE TITLE
Unable to list S3 buckets while using ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3

### ISSUE THREAD

**Issue by rgmehetre** [charleszipp/azure-pipelines-tasks-terraform#281]
Unable to list S3 buckets while using ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3 in Azure DevOps Release pipeline.

We have S3 buckets in us-east-2 region and the user configured in service connection has appropriate permissions on S3 buckets but still it returns with "No results found".

**Comment by jason-johnson** [comment]
The Repo for that task is [here](https://github.com/microsoft/azure-pipelines-terraform).
