### ISSUE TITLE
Hey Team, I am trying to use remote module with Terraform Cloud and Terraform Init command fails with unauthorized error

### ISSUE THREAD

**Issue by pshahid1** [charleszipp/azure-pipelines-tasks-terraform#282]
I have created .env file with TF_TOKEN_app_terraform_io environment variable
I have terraform.rc files in my repository that has credential block to terraform cloud api token. I don't know what else to try here and make this work.
I appreciate any help here.

**Comment by jason-johnson** [comment]
This repository is only for the Azure Devops extensions for calling terraform.  And the issues here are for reporting bugs or requesting features.  I believe StackOverflow would be a more appropriate place for your question.

Thanks
