### ISSUE TITLE
Please, how can I get the vsix file for this extension

### ISSUE THREAD

**Issue by oralcj** [charleszipp/azure-pipelines-tasks-terraform#283]
**Describe the bug**

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
2. Execute pipeline
3. See error

**Expected behavior**

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: [e.g. ubuntu debian]
 - Hosted/Self Hosted
 - Terraform version used (Default for hosted agent is acceptable)
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

**Comment by oralcj** [comment]
Please, how can I get the vsix file for this extension

**Comment by jason-johnson** [comment]
Are you reporting a bug?  The above is just the issue template.  What are you trying to do?

**Comment by oralcj** [comment]
Not really, I think I have figured out how to get it. Thank you
