### ISSUE TITLE
Update test automation to use secure files with spaces in their name

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#29]
Update the test automation to use a secure file whose name has a space to ensure the terraform command still works appropriately. There is a concern that if a secure file has a space, quotes may need to be added around the secure file input.

**Comment by charleszipp** [comment]
While implementing #28, the renamed the secure files for the agents to have spaces in their name. 

![screenshot 58](https://user-images.githubusercontent.com/4292559/53660825-6e634700-3c24-11e9-89c3-85b2880a0e90.jpg)

**Comment by DenWin** [comment]
I would suggest, to remove this particular warning, but to add an additional command "version" which only purpose would be to check the version and  to output this warning - but on purpose.

**Comment by DenWin** [comment]
didn't knew it passes through straight into here. I'm looking into the issue with the error
