### ISSUE TITLE
Feature request: pretty plan

### ISSUE THREAD

**Issue by cveld** [charleszipp/azure-pipelines-tasks-terraform#293]
Your plan tab is already providing great value. Thanks for that!

I just stumbled upon this plan renderer:
https://github.com/cloudandthings/terraform-pretty-plan

Maybe you can incorporate that.

Most importantly it provides collapsible/expandable sections per resource.

They blogged about it here:  https://link.medium.com/MnBV9iSS0ub

**Comment by jason-johnson** [comment]
I can't use the code there due to how it's structure but it did show me how simple reading the `show` output will be.  This is now covered by #376
