### ISSUE TITLE
Support review and approval between plan and apply

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#3]
# Description
When a release is being performed, a terraform will create a plan for what changes will be applied before actually applying them. This feature would pause the release activity for a review and approval after this plan has been created but, before the plan is executed/deployed.

# Justification
This is important for creating an audit trail of what changes are made to environment for each release. Most organizations will have gatekeepers/approvers for downstream environments. This would give them the ability to review the planned changes and sign-off on those changes. Additionally, Azure DevOps would capture and record the plan (in the form of the deployment log) and the person that signed off on the plan (in the form of a deployment approval).

**Comment by dcopl** [comment]
Been working on this particular point for my pipeline. The below points are what I'm trying to achieve to create a build/release for my terraform with appropriate validation before deployments.

1) The build phase installs, initialises then runs and outputs a plan file
2) The build phase publishes the plan file as an artifact
3) The release phase supports approval gates to allow only certain approvers to deploy the plan generated in a build (this is native functionality of Azure DevOps and works well)
4) The release phase uses the plan artifact from the build phase to execute explicit steps after approval

I've been able to get points 1-3 working with your extension but I can't get point 4 to work right. I think an additional parameter to the apply CLI is required to specify the plan file/directory. If I try to use the "Command Options", I don't have any success as the Terraform apply command does not have a named parameter for a plan/directory to target. I end up with a command like this:

terraform apply <path-to-plan> -auto-approve -var-file=/home/vsts/work/r1/a/_DBU-ITOSS-Cyberark-Terraform-CI/terraform_build/production.tfvars


Let me know if you need help with working on this extension and I can try find some time. It seems to work better than the other ones currently on the marketplace in my opinion.

**Comment by charleszipp** [comment]
@dcopl I did some testing this morning and it appears you can specify the [dir-or-plan] param that terraform apply allows using the command options input. However, i did find an issue where the args in command options are placed before the -var-file arg set by the variable file input parameter. So you end up with 
```
[command]/usr/local/bin/terraform plan /home/vsts/work/r1/a/_sample-ci/drop/plan -var-file=/home/vsts/work/r1/a/_sample-ci/drop/default.vars
```
This reinforces your suggestion of having a dedicated input parameter for the plan. That would allow for placing that param at the end of the args string as terraform apply expects.

**Comment by MaxMelcher** [comment]
IMHO: I think it is not this tasks responsibility to handle this matter - and it will be hard to solve this in a good way with build/release tasks. 

I tried two approaches today: 
1. I wrote a [powershell](https://gist.github.com/MaxMelcher/18ef8e3cfa3113e497360ad20eefd137) that extracts the terraform plan output and added it to the build artifact. Then I tried to add this in a reviewable manner to a release pipeline - and did not come up with something nice. The approval email cannot be changed nor can the approval page be adjusted to show meaningful information: 
![image](https://user-images.githubusercontent.com/1029559/51078067-f3fc5900-16af-11e9-8936-e7ba4d28b27f.png). Super easy to click on approve w/o seeing what is being changed. 

2. I copied the approach of [Atlantis](https://www.runatlantis.io/) that reacts on a pull request and comments back the plan output. ![image](https://user-images.githubusercontent.com/1029559/51078017-2063a580-16af-11e9-9a3c-566f7e13577e.png)

Diving into the Atlantis approach I noticed the issue, that multiple builds in Azure DevOps can be run in parallel and there is no way to lock this like Atlantis does it:  
Imagine one build sets the tag of a resource group to value A and the next commit/build set it to value B. Now both builds need to be approved: the order of approval decides then what the final value of the tag will be and could be different to the committed value. 

Do I overengineer this? Would love to see this in this extension but I dont see the extensibility point Azure DevOps from a build/release task perspective.

**Comment by charleszipp** [comment]
@MaxMelcher 
Your first strategy/approach was more in line with how I thought this may work. 
First, since plan is bound to an environment, it does not make sense to me that it should ever be something produced by the build and become a build artifact. This would only ever work if all the environments were always in an identical state with identical configuration, sku's etc. This approach is a bit Utopian in its premise and not practical for most shops (in my experience at least). This leads me to disagree with the Atlantis approach

That leaves this only being created as part of the release (the first part where Azure DevOps has any knowledge of an environment). I was hoping that within a stage, we could run plan in one agent job, and save it to the artifacts, then use the agentless job for a manual approval step. The last job would apply the plan. However, the issue becomes exactly as you found. How do you review the plan in a way it wouldnt be overlooked and/or, even worse, reveal secrets (raw plan file i believe has keys/passwords). There really isnt a good solution for this at the moment.

What would help is if Azure DevOps allowed for CLI interaction/input. For steps that run cli's such as terraform, helm, npm, etc. When the CLI prompts a question, we likely know what it will be and could indicate in the task code what buttons to show and how to translate those back as input to the cli. I would like to try to pass this along to CSE's EEST team for feedback.

Thats a long winded of me saying I agree with your assessment at this stage. I really appreciate you taking a look into this and offering your advice. If you are looking for something else to work on i would suggest #20 or #22. 

Closing this issue for now unless someone else can offer better justification and/or solution to implement.

**Comment by conork123** [comment]
@MaxMelcher I know this was a while ago now, but are you able to share your work on commenting back on a pull request with terraform plan details?
