### ISSUE TITLE
Allow terraform buildagent to support custom providers

### ISSUE THREAD

**Issue by krazineurons** [charleszipp/azure-pipelines-tasks-terraform#30]
Where can i find the instructions to configure the terraform buildagent to have custom providers that are not officially supported?

**Comment by charleszipp** [comment]
@krazineurons 

I want to first clarify that the build agent is not something the task specially provisions. It uses the build agent defined in the pipeline as any other azure devops task would. If you set the pipeline to use a hosted windows agent, thats what the task uses. Therefore, you are still in complete control of the agent.

In most cases, when your build requires specific software installed on the agent, the general recommendation is to not use a hosted build agent. You could instead use your own server as a build agent. This would allow you to install the custom/third-party providers onto the build agent ahead of time without having to define steps in the pipeline for it. This is what i would recommend for a short term solution. See [Self-Hosted Build Agent Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install)

If running your own build agent is not an option, then the other route could be to make installing the custom provider software part of the pipeline. According to the [terraform docs](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) this is done simply by copying the compiled provider to a directory on the machine. You may be able to accomplish this fairly easily by publishing your provider as a [Universal Artifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages) in azure devops. There is a task that allows you to download a Universal Artifact to a directory of your choice on the agent. Alternatively, if you could also write shell/powershell task that downloads the provider from a publically accessible location to the appropriate location on the agent.

There are not currently plans to add first class support for custom providers. However, I would welcome feedback on how you might expect the task to facilitate use of custom providers. For example should it have a field that accepts a list of url's to dependent custom providers?

**Comment by charleszipp** [comment]
Closing until more use cases for feature
