### ISSUE TITLE
State not being written to Azure rm

### ISSUE THREAD

**Issue by ultramekon** [charleszipp/azure-pipelines-tasks-terraform#33]
On my init task I have specified a backend type of azurerm and entered the Resource Group Name, Storage Account Name, Container Name and Key, but the state information is always stored locally. It never writes to the Azure blob store.

**Comment by charleszipp** [comment]
Hey @ultramekon can you please provide the following?

- A zip of your terraform templates directory. Feel free to redact any sensitive data.
- Build/Release log output from the init task (the one where you configure the backend)
- The task definition for  the input task. This should show what you defined for the resource group, the current working directory, the azure subscription, etc.

While i look at these, i would also ensure that your main.tf at the root of your executing directory has the terraform block defined as follows. This block is required to allow it to use a remote backend. The task alone will not add this for you. Also, if you have this make sure its defined as "azurerm" not "local".
```
terraform{
    backend "azurerm" {
    }
}
```

**Comment by ultramekon** [comment]
Hi, thanks for the response. I think the error was probably mine
