### ISSUE TITLE
publishPlanResults in Releases ?

### ISSUE THREAD

**Issue by ultrajericho** [charleszipp/azure-pipelines-tasks-terraform#332]
**Describe the bug**
Quick question (sorry if it's not the right place), Is it normal that when naming Publish Plan Results Name, no "Terraform Plan" tab appears in the Azure Release?
Is this a feature that only works with YAML Pipelines (so for Builds and not Releases)?

**To Reproduce**
1. I set a name in the "Publish Plan Results Name" field
2. Execute release stage
3. Release with the "Terraform plan" task succeed
4. The logs indicates that the Plan (with the name I passed in the "Publish Plan Results Name" field) is returning the following warning : [warning]Plan 'Plan-StorageAccount' is going to create 4 resources.
5. There is no "Terraform Plan" tab created anywhere in the Release.

**Expected behavior**
I want to know if this feature only works in build Pipelines / YAML pipeline and if there is a way to do something clean in Releases .

**Pipeline Logs**
2023-03-03T16:45:35.2365997Z ##[warning]Plan 'Plan-' is going to create 4 resources.
2023-03-03T16:45:35.2375260Z ##[debug]Processed: ##vso[task.issue type=warning;]Plan 'Plan-' is going to create 4 resources.

**Agent Configuration**
 - OS: Windows Server 2019
 - Self Hosted
 - Terraform version 1.3.9
 - AzureCLI version used 2.45.0

**Comment by ultrajericho** [comment]
This guy managed to make the Terraform Plan work with his extension : https://marketplace.visualstudio.com/items?itemName=JaydenMaalouf.terraform-output

Maybe you can do the same enhancement with this one.

**Comment by ultrajericho** [comment]
Here is the pullrequest/commit he made to fix this : 
https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/commit/41b40d49328338014fb1113b4173c49e5f4f53e6

**Comment by jason-johnson** [comment]
Will resolve this via #339
