### ISSUE TITLE
Unable to download Terraform Module repo from Source repo using Charles Zipp terraform cli

### ISSUE THREAD

**Issue by akanade07** [charleszipp/azure-pipelines-tasks-terraform#343]
We are facing intermittent issue with cloning terraform module repo from source code repo in Azure DevOps. Getting below error while trying to download module in terraform Init step. 

D:\AdosBuilds\ADOS-AzAgent1\_tool\terraform\1.3.6\x64\terraform.exe init -backend-config=storage_account_name=ststfbackendcasdbdev -backend-config=container_name=terraform-db-dev-state -backend-config=key=terraform-db-dev.tfstate -backend-config=resource_group_name=rg-centro-engineering-spoke-dev-001 -backend-config=subscription_id=30ef14ef-8bf6-4afd-a9e1-f1fe6d06b974 -backend-config=tenant_id=dd63fb60-07f6-4d96-8d40-ebeca61a524e -backend-config=client_id=*** -backend-config=client_secret=***
Initializing modules...
Downloading git::https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main for azurem_cosmosdb_cassandradb_api...
Downloading git::https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main for azurerm_private_endpoint...

│ source code from
│ "git::[https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main"](https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main%22):
│ error downloading
│ '[https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main'](https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules?ref=main%27):
│ C:\ADOS-Agent1\externals\git\cmd\git.exe exited with 128: Cloning into
│ '.terraform\modules\azurem_cosmosdb_cassandradb_api'...
│ fatal: unable to access
│ 'https://dev.azure.com/WFRD-RDE-DWC-Software/CENTRO-Engineering/_git/OneSync_Azure_TF_Modules/':
│ The requested URL returned error: 403

[logs_428.zip](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/files/11440586/logs_428.zip)

**Comment by jason-johnson** [comment]
Hi @akanade07, why do you think this is an issue with the extension?  If you try to run terraform with e.g. bash, does it work in the pipeline?  This looks like a pipeline issue (e.g. have you verified that the same agent types are used for the working and the failing runs?).

**Comment by jason-johnson** [comment]
No answer and this appears to be an issue with the agent, not the extension.  Closing.  If there is more to add, feel free to re-open with additional information.
