### ISSUE TITLE
A new enhancement integrated into the Oracle Cloud platform. - NEW FEATURE

### ISSUE THREAD

**Issue by mgalvao-git** [charleszipp/azure-pipelines-tasks-terraform#346]
Greetings! Firstly, I would like to express my appreciation for the excellent code, as it has proven to be highly efficient and beneficial on both the GCP and Azure platforms, which we are already adept at utilizing.

Now, I would like to inquire about the feasibility of incorporating versioning functionality specifically for OCI (Oracle Cloud Platform). While we have attempted to adapt the code, it is not functioning in the same manner as it does on GCP and Azure.

thank you so much

**Comment by jason-johnson** [comment]
Hi, thanks.  This extension just calls terraform commands in Azure Devops pipelines, it doesn't have any Azure or GCP specific code.  What is not working?

**Comment by jason-johnson** [comment]
@mgalvao-git did you see the question above?

**Comment by jason-johnson** [comment]
Appears this is not related to this extension.  Please comment if this is not the case and we can re-open.
