### ISSUE TITLE
Terraform CLI create only container for backend if storage account exists - IMPROVEMENT

### ISSUE THREAD

**Issue by akordowski** [charleszipp/azure-pipelines-tasks-terraform#348]
The Terraform CLI `init` command contains the `Create Backend (If not exists)` option. When set to `true` the Azure CLI tries to create a Resource Group and a Storage Account with a Container. But if the Storage Account already exists the command fails. It would be a great improvement if the container is created when the Storage Account already exists.

An other improvement would be also a option to set the verbosity level for the Azure CLI, when running the `Create Backend` command.

**Comment by jason-johnson** [comment]
Hi @akordowski.  The "Create Backend" functionality is not a production level feature.  It is just for convenience when testing and, honestly, I'm probably going to remove it entirely as it's not really appropriate for the extension.

For use cases where the storage account will be created before the terraform run, I would suggest an AzCli step before terraform to set up the storage account and container exactly as needed.  But in all the installations I've ever worked with, the storage account and container are created as part of the application provisioning and would not be modifiable by the pipeline which runs terraform.
