### ISSUE TITLE
Format Terraform files using "fmt" command need "environmentServiceNameXXXX" parameter.

### ISSUE THREAD

**Issue by aloizeau** [charleszipp/azure-pipelines-tasks-terraform#351]
**Describe the bug**
I want to use **fmt** command from custom option but the task want unnecessary "environmentServiceNameXXXX" parameter.

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
`
- task: TerraformTaskV4@4
        displayName: 'Format Terraform files'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: './terraform'
          customCommand: 'fmt'
          outputTo: 'console'
          # environmentServiceNameAzureRM: 'MyAzureService'
`
3. Execute pipeline
`
Starting: TerraformTaskV4
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 4.218.21
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AAf0uqr)
==============================================================================
##[error]Error: Input required: environmentServiceNameAzureRM
Finishing: TerraformTaskV4
`

**Expected behavior**
"environmentServiceNameXXXX" parameter must be optionnal on standard Terraform fmt command.

**Pipeline Logs**
`
Starting: TerraformTaskV4
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 4.218.21
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AAf0uqr)
==============================================================================
##[error]Error: Input required: environmentServiceNameAzureRM
Finishing: TerraformTaskV4
`
**Agent Configuration**
 - OS: 'ubuntu-latest'
 - Self Hosted
 - Terraform version used: terraform 1.5.1 x64
 - AzureCLI version used: 2.49.0

**Comment by jason-johnson** [comment]
TerraformTaskV4 is not part of this extension.  It's part of [this one](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks).  This extension is found [here](https://marketplace.visualstudio.com/items?itemName=JasonBJohnson.azure-pipelines-tasks-terraform) and does not have the problem you describe.
