### ISSUE TITLE
Create Storage account (TF state) with Infrastructure enabled

### ISSUE THREAD

**Issue by SPALLADI** [charleszipp/azure-pipelines-tasks-terraform#368]
**Describe the bug**
I am using your extension in our Pipelines. Terraform init with in the extension creates storage account for TF state files. For our project we need our Storage account to have Infrastructure Encryption enabled. Do you have option for this?
az storage account create \
    --name <storage-account> \
    --resource-group <resource-group> \
    --location <location> \
    --sku Standard_RAGRS \
    --kind StorageV2 \
    **--require-infrastructure-encryption**
**To Reproduce**
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/94529039/fff4d361-a799-47ba-8ee2-afdb43f094ad)

**Expected behavior**
I expect to create the Storage account with infrastructure enabled

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: [e.g. ubuntu debian]
 - Hosted/Self Hosted
 - Terraform version used (Default for hosted agent is acceptable)
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

**Comment by jason-johnson** [comment]
Hi @SPALLADI, thanks for the issue.  In this case, wouldn't it be better to go ahead and create the storage account with your specific needs outside of the pipeline?  Or at least in a separate step in your pipeline.

`ensureBackend` is a convenience feature but it's not intended to support every option storage accounts have (e.g. setting up private endpoints, CMK's, etc.).
