### ISSUE TITLE
TerraformCLI@0 doesnt work anymore, pipelines broken

### ISSUE THREAD

**Issue by detox3r** [charleszipp/azure-pipelines-tasks-terraform#379]
**Describe the bug**
Some of our pipelines are still using the TerraformCLI@0 task. it looks like this doesnt work anymore and all our pipelines are broken.

TerraformCLI@1 works fine.

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
2. Use TerraformCLI@0 in any ADO pipeline GUI
3. See error only in ADO. vscode still sees TerraformCLI@0 as valid

**Expected behavior**
TerraformCLI@0 should also work 

**Screenshots**
<img width="1212" alt="image" src="https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/76015484/8693afe1-d433-42a8-8400-1640f9f687e5">

**Pipeline Logs**
no needed

**Agent Configuration**
 - OS: ubuntu-latest
 - Hosted

**Additional context**
A deprecation notice would've been nice

**Comment by jason-johnson** [comment]
Hi, sorry about that.  This is part of the ongoing work to support multiple versions of the pipeline, which should allow us to release faster going forward.  In the future the different versions will be different SLA's.  `0` should be the previous `0.7` release, `1` will be the latest stable `1.*` release.  2 will be unstable changes currently being tested, etc..

**Comment by jason-johnson** [comment]
Related to #389

**Comment by jason-johnson** [comment]
Hi @detox3r , this is now clarified in #392

**Comment by Clockwork-Muse** [comment]
Part of the problem currently is that the documentation shows `TerraformCLI@0`, which makes it look like a drop-in replacement.
That's not the case....

**Comment by jason-johnson** [comment]
The documentation should be correct now. Please make an issue if you see places that are misleading. @0 should work fine now.
