### ISSUE TITLE
Improvement: Update read me to show examples with version 1

### ISSUE THREAD

**Issue by jaredfholgate** [charleszipp/azure-pipelines-tasks-terraform#381]
**Describe the bug**
The read me shows version @0 in various places, including screen shots and some sample code. We should update the read me to show version @1 everywhere to avoid confusion for consumers.

**To Reproduce**
1. Open the read me
2. Read it

**Expected behavior**
The read me should specific version @1 as this is the stable and functional version.

**Screenshots**
N/A, looks at the read me.

**Pipeline Logs**
N/A

**Agent Configuration**
N/A

**Additional context**
See related issue here: https://github.com/Azure-Samples/azure-devops-terraform-oidc-ci-cd/issues/3

**Comment by jason-johnson** [comment]
I would say we wait and implement the multi version approach. The documentation has to have a going over then anyway.

**Comment by jason-johnson** [comment]
Will be resolved by #389

**Comment by jason-johnson** [comment]
Solved in #392
