### ISSUE TITLE
Please update Terraform version

### ISSUE THREAD

**Issue by azurecloudio** [charleszipp/azure-pipelines-tasks-terraform#40]
Dear all

I'm a greenhorn. Could someone update the terraform.exe, please?

Error: ‌
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.12'

Please run at least that version of Terraform to continue.

##[error]Error: The process 'C:\hostedtoolcache\windows\terraform\0.11.11\x64\terraform.exe' failed with exit code 1
##[section]Finishing: terraform init

**Comment by charleszipp** [comment]
Hey @azurecloudio, you should be able to to update the version of terraform used yourself by using the terraform installer task. I am guessing that you are probably using the version of terraform installed on the agent. I believe you can override this using the Terraform Installer task and putting the version needed in the version field (for your case 0.11.12). The Terraform Installer task should precede any Terraform CLI tasks.

Please update this thread with your findings after trying these suggestions.

Sample YAML
```yaml
steps:
- task: TerraformInstaller@0
  displayName: 'Use Terraform 0.11.12'
  inputs:
    terraformVersion: 0.11.12
``` 
![screenshot 62](https://user-images.githubusercontent.com/4292559/54127549-08bb4b80-43d8-11e9-925b-bbab087b4734.jpg)
![screenshot 61](https://user-images.githubusercontent.com/4292559/54127550-0953e200-43d8-11e9-9e06-cebb396f4189.jpg)
