### ISSUE TITLE
How to authenticate using Service Principal and certificate in the terraform task in azure pipelines.

### ISSUE THREAD

**Issue by sudhir-ops** [charleszipp/azure-pipelines-tasks-terraform#401]
**Describe the bug**
Is it possible to authenticate via service principal and certificate in terraform task? So far, I'm seeing only service connection is available for authentication.

By the method provided in below link, is it possible to input values in to terraform task and authenticate?

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate

**Comment by jason-johnson** [comment]
Duplicate of #270
