### ISSUE TITLE
The author is still Charles Zipp

### ISSUE THREAD

**Issue by gherasim-learn** [charleszipp/azure-pipelines-tasks-terraform#409]
Hello, I have no idea if it is intentional but the Author is still Charles Zipp.
Is it ok like that or am I doing something wrong?
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/75733876/c855c1bd-5b6b-40f8-9023-d4d4946e3286)

**Comment by jason-johnson** [comment]
I left that because Charles is the author.  I am now the maintainer but I didn't write the code.
