### ISSUE TITLE
Input plan file in command line arguments breaks terraform apply 

### ISSUE THREAD

**Issue by paultowers** [charleszipp/azure-pipelines-tasks-terraform#41]
The `-auto-approve argument`  is automagically suffixed as a command line argument to the user defined command line arguments.  When using an input file from a previous terraform plan command, the terraform apply command fails with error: **"Too many command line arguments. Configuration path expected."**

Command line syntax is `terraform apply [options] [DIR-OR-PLAN]`

`-auto-approve` needs to be injected into the command line in the proper sequence and not just suffixed on.

**Comment by charleszipp** [comment]
Thanks @paultowers for taking the time to open the issue. I will investigate this week to see if I can repro and get a fix that at the very least puts the -auto-approve in the appropriate position relative to the plan output path.

**Comment by Alexlofern** [comment]
Hi, same error for me... 

![image](https://user-images.githubusercontent.com/27426979/54225803-3fc65580-44db-11e9-9cc6-de3841836f68.png)

Please, when you can fix this issue?

Regards

**Comment by charleszipp** [comment]
@Alexlofern @paultowers  I will be looking into this today. I will post an update once I have more information

**Comment by charleszipp** [comment]
@paultowers @Alexlofern I have pushed a fix for this with version 0.4.3. The new version has been uploaded to the marketplace which (I believe) should update the extension within your org/account automatically. Please give this a try and let me know if the fix resolved your issue

**Comment by Alexlofern** [comment]
tkx, I'll test on next week, don't have windows now....
