### ISSUE TITLE
Multi region AWS Services?

### ISSUE THREAD

**Issue by brandonbrinkley** [charleszipp/azure-pipelines-tasks-terraform#410]
Hello! We are still using the old (Charles Zipp) extension that this one replaces and looking to upgrade. One of the driving factors is the need to deploy multi-region services like global Aurora databases. Does the latest release have in any issues with doing this? Does anyone happen to have some documentation or examples using Aurora?

Thanks!
Brandon

**Comment by jason-johnson** [comment]
@piizei  can you comment to this one?

**Comment by piizei** [comment]
There is no difference between the old and the new versions that I'm aware of why it would or would not work.
I'm speculating here (have not tested this) but I think the AWS_REGION configuration is for the backend connection. The Aurora multi-region resource looks like any other terraform resource. 
So my educated quess is that it should work, but please report back if you test it 😄

**Comment by jason-johnson** [comment]
Hi @brandonbrinkley, any update?

**Comment by jason-johnson** [comment]
No response from requestor, closing.  If there is anything else to do here please let us know.
