### ISSUE TITLE
Azure Pipelines Terraform Tasks - Charles Zipp

### ISSUE THREAD

**Issue by jamesbond0008** [charleszipp/azure-pipelines-tasks-terraform#413]
Can you please confirm if you have deleted the Azure Pipelines Terraform Tasks - Charles Zipp extension from the marketplace and when this was completed?

As I was using this for my current environment, pipelines have now broken and now require to install a new extension.

**Comment by jason-johnson** [comment]
I did not delete it, I disabled it.  If you are currently using the old one it should still run, it just won't get any new updates.

**Comment by jamesbond0008** [comment]
Thank you, can you confirm when it was disabled?
