### ISSUE TITLE
Use TF_IN_AUTOMATION: 'True' by default

### ISSUE THREAD

**Issue by RockyMM** [charleszipp/azure-pipelines-tasks-terraform#416]
This is an improvement request.

It would be nice that the environment variable `TF_IN_AUTOMATION` is set to `True` by default.

**Comment by captainhook** [comment]
Does this also apply the '-no-color' argument to fix the encoding issue in Azure DevOps logs?

**Comment by RockyMM** [comment]
To be honest, I have no issues with the color output in my logs.
