### ISSUE TITLE
Update azure-pipelines-task-lib to latest

### ISSUE THREAD

**Issue by riemers** [charleszipp/azure-pipelines-tasks-terraform#419]
Please update the azure-pipelines-task-lib to i think 4.10.0 as this resolves a lot of security issues.

That would at least fix mockery which is like 7 years old ;p work in a big company and alert bells go off etc ;)

![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/682041/0f29cd60-9f4e-4471-9be3-03bf22aadd64)

Inside:
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/682041/fd83174f-4393-4a40-b05e-f333ee7895f8)

I think if you change [this](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/51376af42ffc143ce86d50c0fc31ad5843878621/tasks/terraform-installer/package.json#L37) to something like ^2.0.0 then we are all good again, thats the source from what i can tell that calls the old one.

**Comment by captainhook** [comment]
@jason-johnson any update on this? Happy to do a PR but is there anything else holding this back?

**Comment by jason-johnson** [comment]
A PR would certainly speed up the process. I just need to make sure the PR doesn’t break anything. I’m in the process of moving more of the pipeline to GitHub so you get immediate feedback on errors.

**Comment by jason-johnson** [comment]
Fixed by #459
