### ISSUE TITLE
Allow for different storage account types

### ISSUE THREAD

**Issue by scott1138** [charleszipp/azure-pipelines-tasks-terraform#42]
The parameter kind is hard-coded to blobstorage.  This can be a problem for someone with an existing  storage account who would like to continue keeping their state files together, but perhaps in separate containers.  A drop down to select the storage type\kind would be great.

**Comment by charleszipp** [comment]
@scott1138 

I believe this should be a simple adjustment to allow for this. Can you send me the CLI commands or ARM template for the storage account being used? This will help in testing two areas. First, I can repro not being able to use a storage account created the same way your's is. Second, I can ensure after the change is implemented, its now possible to use that same storage account.

Thanks for taking the time to provide this feedback!

**Comment by scott1138** [comment]
The command you are using is:
az storage account create --name <name> --resource-group <rg_name> --sku Standard_RAGRS --kind BlobStorage --encryption-services blob --access-tier hot

Simply changing --kind to "StorageV2" will cover most scenarios (like mine) but also allowing for "Storage" will cover people with older accounts.

Perhaps performing "az storage account show --name <name> --resource-group <rg_name>" and only creating the account if it does not exist might be the most graceful way to handle existing accounts.

**Comment by charleszipp** [comment]
Thanks for taking the time to provide the info @scott1138. I especially like your suggestion about checking if the storage account exists first. I think this may actually be the shortest path to get us past this issue. Additionally, this would be good to have in there despite this issue. 

I will try this method to see if that can get us past the issue. If not, I will add a field to specify the storage account kind.

**Comment by charleszipp** [comment]
@scott1138 i have a PR ready with the the only create if not exists approach. I found this also makes sense as the azure cli create command will modify the storage account if different values are provided. This is not always allowed which is the reason for the errors you encountered. However, I dont think users would expect this to happen and could be viewed as unsafe. Therefore, i think simply not running the create command if the account exists is needed regardless. 

If i find users are needing to specify the kind themselves even after having this change, i will add the ability to specify the kind as a separate enhancement.

I should have this merged and released tomorrow.

**Comment by charleszipp** [comment]
Released with 0.4.4

**Comment by paultowers** [comment]
2 cents @charleszipp I would open up kind as an option.  Thanks for fixing it, I to was hitting this same problem
