### ISSUE TITLE
Severe Security flaw: OIDC Token printed as Plain text in the pipeline run log for Service Connections configured with Workload Identity Federation

### ISSUE THREAD

**Issue by hari2anand** [charleszipp/azure-pipelines-tasks-terraform#428]
**Describe the bug**
TerraformCLI@1 task prints the OIDC token as is in plain text when performing init, plan and apply, which is a serious security risk! as anyone having pipeline read access can simply copy paste the token to mimic the App-Reg and gets its access in azurerm.

**To Reproduce**
  - task: TerraformCLI@1
    name: terraformPlan
    displayName: "Terraform: Plan"
    inputs:
      command: plan
      environmentServiceName: test-wif-sc
      providerAzureRmSubscriptionId: "xxxx"
      runAzLogin: true
      allowTelemetryCollection: false
This prints the token in run log
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/45207514/185fe6c3-816b-463b-b65a-9de7ff2645b4)

**Expected behavior**
Token should be masked like the username!
**Screenshots**
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/45207514/4214c8cc-4ceb-4496-9b40-6750d3d756de)

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.
Can't attach due to sensitive content!
**Agent Configuration**
 - OS:  ubuntu 
 - Self Hosted
 - Terraform version used 1.7.5
 - AzureCLI version used 
**Additional context**

**Comment by jason-johnson** [comment]
@jaredfholgate can you reproduce?

**Comment by jason-johnson** [comment]
For me the token is hidden in every place I checked.  I don't have a self hosted agent to check on though.

**Comment by vanchogeorgievski** [comment]
Thanks for looking into this @jason-johnson . Can we get anyone from Microsoft to try and reproduce this issue? They should have plenty of self hosted runners :D Ping @jaredfholgate

**Comment by hari2anand** [comment]
Thanks for looking into the issue. I validated recently on the latest versions and can no longer see the tokens! Looks it's fixed in one of the recent releases. This issue is good to close :) 
![image](https://github.com/user-attachments/assets/c1311185-27e2-4cdc-934c-8b5cf7c52749)
![image](https://github.com/user-attachments/assets/6a4cab3f-f972-4104-9815-59ab06cd4c8f)
