### ISSUE TITLE
Add backend type to allow use of self-configured backend (via template, envs, and/or backend-config options)

### ISSUE THREAD

**Issue by andrew-sumner** [charleszipp/azure-pipelines-tasks-terraform#43]
Original statement provided by @andrew-sumner. Re purposing as a placeholder for enhancement
> I use the artifactory backend and everything required is defined in my terraform configuration, but it seems that this task will ignore that.

As a user, I would like a backend type option that only uses backend configuration I provide (via templates, env vars, and/or backend-config options), so that I can use backend types that are not yet supported.

User will specify the actual backend type (terraform enterprise, artifactory, s3, etc) within their terraform template. This will drive how terraform knows what type to use. Then, the user will be able to provide the configuration options for the backend by specifying it within the template, as `-backend-config=` option in the Command Options input, and/or environment variables. Terraform allows the collective backend configuration to be split across these different locations.

**Comment by charleszipp** [comment]
@andrew-sumner 
Can you provide more details about how you are configuring your backend? Is this via env vars or do you have the configuration in your templates (.tf) files? Also, can you provide either the YAML or a screen shot on how you are setting up the init task in your pipeline?

I believe you may be able to work around this by setting the backendType to local. That option will essentially run terraform init with no args. Therefore, if you have the backend configuration set via env vars or in a template, that should allow it use those.

**Comment by andrew-sumner** [comment]
My Terraform configuration file contains:

```
terraform {
  backend "artifactory" {
    username = "srv-ice-artifactory"
    url      = "https://artifactory2.company.co.nz"
    repo     = "generic-ice-terraform-local"
    subpath  = "FunctionApp/DevTT"
  }
}
```

On the Terraform CLI Task I have set:

**Command**: init
**Options**:  -backend-config="subpath=FunctionApp/$(Release.EnvironmentName)"  -backend-config="password=$(ARTIFACTORY_PASSWORD)" 
**Backend Type:** local _- just not sure what impact that might have..._

The goal being that the state file is separated for each environment I deploy into, and stored in artifactory.  

I probably could use AzureRM but our corporate standard currently is Artifactory and even that may yet change to the Terraform Enterprise backend in the future.

**Comment by andrew-sumner** [comment]
Using a backend type of local works as you suggested.  It's the only non-intuitive setting that I've found.  

Thanks for your support and for developing this plugin!

**Comment by charleszipp** [comment]
No problem @andrew-sumner. Glad you were able to find a solution on this one as well. 

I agree using local for this purpose is not intuitive. That's because local type was not originally developed for this purpose. However, this is becoming more common that people are using the local type as sort of an escape hatch, Just as you did, I have seen others use local to allow them to use a backend that isn't supported like AzureRM. I have been trying to come up with a way to re-label local to indicate this is possible.

**Comment by favoretti** [comment]
If I understand this correctly, #125 should address this, as this is pretty much why I wanted to be able to set env vars during init stage - to allow for self-configured backends to function.

**Comment by charleszipp** [comment]
+1 to @favoretti, while the drop-down is still not intuitive, you can use local + .env file in the variables section to configure a remote backend other than Azure Storage. We probably just need to make a few adjustments on the Task UI/YAML to make this more obvious that it can be done.

I am going to leave this open for reasons above. I believe we need to add a `self-configured` option to the backend type drop-down and add some docs about how this is intended to be used.

**Comment by favoretti** [comment]
I can take this one. I’ll remove deps on backendAzureRm in plan/apply if
backend is self-configured then as well if that’s ok with you.

**Comment by charleszipp** [comment]
@favoretti please see my comments in #127 regarding the dependency you are talking about. I am fine with you adding the self-configured option in the drop-down

**Comment by favoretti** [comment]
@charleszipp Let's do it 2-step. I just added part with `withAzureRmProvider` to refresh, let's get these two merged, then I'll do the self-configured overhaul, it's a bit many places to change, don't wanna have overlapping PRs live at the same time.

**Comment by charleszipp** [comment]
@favoretti will be working on a change that should accommodate this.
