### ISSUE TITLE
Node 16+ support

### ISSUE THREAD

**Issue by nwallace83** [charleszipp/azure-pipelines-tasks-terraform#430]
The latest version of the self-hosted pipeline-agent-* (3.238.0) no longer has Node10 installed by default.  Attempting to run this task with the new version of the agent results in the below error.

`##[error]This step requires a node version that does not exist in the agent filesystem. Path: {removed}/externals/node10/bin/node`

Node10 appears to still be included in the vsts-agent-* versions.  I can't find any official announcement of Node10 being deprecated from the agents except this old announcement.

https://learn.microsoft.com/en-us/azure/devops/release-notes/roadmap/2022/no-node-6-on-hosted-agents

**Comment by jason-johnson** [comment]
Is this for [this](https://marketplace.visualstudio.com/items?itemName=JasonBJohnson.azure-pipelines-tasks-terraform) extension?  In the linked issue you mention TerraformTask which is actually [this](https://github.com/microsoft/azure-pipelines-terraform/tree/main) project.  We don't have any task called "TerraformTask" in this extension.

**Comment by jason-johnson** [comment]
Hi @nwallace83, can you confirm you are talking about this extension?

**Comment by nwallace83** [comment]
Yes, this error is from the TerraformCLI@2 task.  I assume this is because only node 10 is allowed in the task.json file

https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/main/tasks/terraform-cli/task.json

```
    "execution": {
        "Node10": {
            "target": ".bin/index.js",
            "argumentFormat": ""
        }
```

**Comment by ArronaxKP** [comment]
With the EOL of Node 10, is there plans to support more recent versions of node?

```
##[warning]Task 'Terraform Installer' version 2 (TerraformInstaller@2) is dependent on a Node version (10) that is end-of-life.
Contact the extension owner for an updated version of the task.
Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

**Comment by jason-johnson** [comment]
Handled by #454
