### ISSUE TITLE
Add support for -backend-config=PATH when using terraform init

### ISSUE THREAD

**Issue by Degooya** [charleszipp/azure-pipelines-tasks-terraform#431]
It would be nice to add support for the backend-config option, when using terraform init, to outsource the configuration of the remote state.

- task: TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: init
    backendType: azurerm
    backendServiceArm: 'My Azure Service Connection'
    backendConfig: $(System.DefaultWorkingDirectory)/remote.conf

**Comment by jason-johnson** [comment]
Hi,

Is the existing [self-configured](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/main/overview.md#remote-local-and-self-configured-backend-state-support) not able to handle this use case?

**Comment by jason-johnson** [comment]
Hi @Degooya , does the linked configuration handle this case?

**Comment by jason-johnson** [comment]
No further response from requester and this case appears to already be covered.  Closing.
