### ISSUE TITLE
Run Terraform Init with azurerm backend using storage account with key-based authentication disabled.

### ISSUE THREAD

**Issue by timothycrall** [charleszipp/azure-pipelines-tasks-terraform#439]
We have recently implemented a policy requiring azure storage accounts to have [key-based authentication disabled](https://learn.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal).  Is there a way to get the TerraformCLI@1 task with command 'init' to connect to this storage account using Microsoft Entra authentication?  Using the command as-is, I get the error `Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account"`

**Comment by jason-johnson** [comment]
This is not a TerraformCLI question but a terraform question.  See [here](https://stackoverflow.com/questions/78295092/terraform-azurerm-backend-is-trying-to-use-key-based-auth-to-connect-to-blob-sto).
