### ISSUE TITLE
"The current operating system is not capable of running this task" since version 1.2.3.1, was ok on 1.2.2.0

### ISSUE THREAD

**Issue by wgkesler** [charleszipp/azure-pipelines-tasks-terraform#458]
Since version 1.2.3.1 `TerraformInstaller@1` and `TerraformCLI@1` tasks are returning the following error:

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

![image](https://github.com/user-attachments/assets/665bd7c9-220b-47df-83cc-77e00747f262)

We have self-hosted agents based on Ubuntu 22.04 on Azure and on AWS, but the problem exists on the AWS only.
We tried to build new image based on Ubuntu 24.04, as well as we tried to use `TerraformInstaller@2` task - the error is the same.

Interesting part is that everything was working properly before, and it was working properly on the version 1.2.2.0 after auto-update for one day, and it is failing since auto-update to version 1.2.3.1.

**Comment by wgkesler** [comment]
Problem solved, in our case the reason was that those agents working on AWS were using the older Azure DevOps Agent version (3.227.1). After upgrading to the newest version (3.248.0) the error was gone.
![image](https://github.com/user-attachments/assets/0bd467f6-af44-426d-a7b7-dca044e001d1)

**Comment by wgkesler** [comment]
After further invastigation, probably the following version requirement should be updated:

https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-installer/task.json#L19

https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-cli/task.json#L19

**Comment by lsanchez-v** [comment]
> Since version 1.2.3.1 `TerraformInstaller@1` and `TerraformCLI@1` tasks are returning the following error:
> 
> ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
> 
> ![image](https://private-user-images.githubusercontent.com/22675518/389491111-665bd7c9-220b-47df-83cc-77e00747f262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDgzNDQsIm5iZiI6MTczMjU0ODA0NCwicGF0aCI6Ii8yMjY3NTUxOC8zODk0OTExMTEtNjY1YmQ3YzktMjIwYi00N2RmLTgzY2MtNzdlMDA3NDdmMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjN2QyNTg3Mjk4MGZhYmQ2N2M2YWVjYWE5Y2FjNGEyNDAzZDQxOTczN2U0MmQ0ODYwY2RkODMyM2IzODY5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vLKeK6ai4pdbTBdcAvVE6diJe2oTxC0G3hHBRHMKCUY)
> 
> We have self-hosted agents based on Ubuntu 22.04 on Azure and on AWS, but the problem exists on the AWS only. We tried to build new image based on Ubuntu 24.04, as well as we tried to use `TerraformInstaller@2` task - the error is the same.
> 
> Interesting part is that everything was working properly before, and it was working properly on the version 1.2.2.0 after auto-update for one day, and it is failing since auto-update to version 1.2.3.1.

Same problem here, it was working with version 1.1.2, and now with version 1.2.3 is failing with the same error:

`##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.`

**Comment by wgkesler** [comment]
@lsanchez-v try to update the agent version, it worked for me.

**Comment by npassmore** [comment]
Also seeing this issue since deployment of 1.2.3.1.  Using DevOps agent "4.248.0"  the issue is resolved, but on older versions i.e. 2.211.0 we see the error.   We are looking to upgrade all our agents, but we have an outstanding bug with MS where we are seeing issues in our CI/CD process, but we may be forced to upgrade if a fix isn't found .. 

2024-11-25T13:08:57.6716037Z ==============================================================================
2024-11-25T13:08:57.6716848Z Task         : Terraform Installer
2024-11-25T13:08:57.6717457Z Description  : Installs a specific version of terraform
2024-11-25T13:08:57.6717893Z Version      : 1.2.3
2024-11-25T13:08:57.6718345Z Author       : Charles Zipp
2024-11-25T13:08:57.6718961Z Help         : 
2024-11-25T13:08:57.6719296Z ==============================================================================
2024-11-25T13:08:57.6893284Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2024-11-25T13:08:57.6908120Z ##[section]Finishing: Install Terraform

**Comment by jason-johnson** [comment]
> After further invastigation, probably the following version requirement should be updated:
> 
> https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-installer/task.json#L19
> 
> https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-cli/task.json#L19

Fantastic find, thanks for that!  Do you know what version should be the new minimum?

**Comment by lsanchez-v** [comment]
> @lsanchez-v try to update the agent version, it worked for me.

Fixed by upgrading the agent's version indeed, thank you @wgkesler

**Comment by jason-johnson** [comment]
> After further invastigation, probably the following version requirement should be updated:
> 
> https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-installer/task.json#L19
> 
> https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/66693231ffafcf2638107cea1e998d41f27cf3fd/tasks/terraform-cli/task.json#L19

I've bumped both tasks to require agent versions 3.248.0.  If anyone can demonstrate that they can run on an earlier version I will change it.

**Comment by npassmore** [comment]
@jason-johnson we had been using agents as old as 2.211.1, we are looking to upgrade these but have been having some issues which Microsoft have been working on... but not found a resolution for as yet ..
