### ISSUE TITLE
Error In creating Resource group If it does not exist

### ISSUE THREAD

**Issue by anand5555** [charleszipp/azure-pipelines-tasks-terraform#47]
I am trying to create a resource group , storage account and upload the tf state file to the blob once the terraform resource is created . The task is failing to create the resource group if it does not exist.  

![image](https://user-images.githubusercontent.com/31290069/54369486-6bb51880-464c-11e9-8a56-0dca4fdd9b9d.png)

**Comment by charleszipp** [comment]
@anand5555 the value for Location should be the short name of the location. The short name for East US is "eastus". Try using that and let me know if that helps. If you are still having issues, please dump the entire log output for the init task and attach it in this issue.

**Comment by charleszipp** [comment]
@anand5555 you can list the region short names using the following az cli command
```
az account list-locations --query [].name  -o table
```

**Comment by anand5555** [comment]
@charleszipp That helped . Thank you.
