### ISSUE TITLE
Do not prompt to input missing variables in pipeline

### ISSUE THREAD

**Issue by dshanahan-bt** [charleszipp/azure-pipelines-tasks-terraform#474]
**Describe the bug**
If a variable isn't set in terraform the terraform task will prompt for a user to input the value on the command line. In the case of devops pipelines this is not desireable/useful - as it results in the pipeline prompting for user input that's not going to come and causes the pipeline to "hang" until the timeout is reached before failing.

Terraform CLI has a `-input=false` argument, which indicates to terraform not to prompt for user input and fail immediately instead of prompting for user input.

Adding `-input=false` to every devops task seems reasonable. The option to toggle on/off (preferably with the default to add it) could also make sense.

This can be worked around with the `commandOptions: -input=false` parameter, but that's a noisy option.

**To Reproduce**
1. Create terraform config with a variable that does not have a default
2. Use a simple pipeline to run a terraform `plan`, `apply`, or similar operation without setting the variable
3. Observe pipeline log will display a prompt to input the value of the variable and eventually time out

**Expected behavior**
Pipeline fails immediately if variable(s) are missing

**Comment by jason-johnson** [comment]
Hi.  I assume you are using version `@1` of the task?  If so, can you check version `@2` and see if it still has this behaviour?  Version 2 has a flag set for automation so it should also skip any prompts but I've not tested this use case.

**Comment by dshanahan-bt** [comment]
I am using the `@2` version

**Comment by dshanahan-bt** [comment]
Some context from a pipeline task:

The start of the task showing the version info:

```
Starting: Terraform 1.9.6 plan
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 2.203.0
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AAf0uqr)
==============================================================================
```

And then the terraform command actually called:

```
C:\hostedtoolcache\windows\terraform\1.9.6\x64\terraform.exe plan -out=plan -detailed-exitcode
```

I would expect to see the `-input=false` in the command line to avoid those prompts.

**Comment by dshanahan-bt** [comment]
I can see now the author's are different I'm pretty sure I'm in the wrong place.

**Comment by jason-johnson** [comment]
Actually, I'm not the original author.  Charles Zipp is.  I took this project over when the original author couldn't maintain it anymore.  I have not yet updated the author because I hadn't contributed enough code to feel like that was honest but I will soon.

**Comment by dshanahan-bt** [comment]
The help in the task points to a different repo https://github.com/microsoft/azure-pipelines-terraform - so I'm pretty sure I was looking in the wrong place.
