### ISSUE TITLE
Environment Azure Subscription should be made optional

### ISSUE THREAD

**Issue by HerrHoller** [charleszipp/azure-pipelines-tasks-terraform#54]
the option to select an azure subscription should be made optional since I would like to run terraform agains our onprem vSphere environment.

**Comment by FirstInternetUser** [comment]
When running the terraform plan, the following error is thrown:

##[error]Error: Input required: environmentServiceName
##[section]Finishing: terraform plan

What is causing this? The init, and validate prior to the plan section works fine.

**Comment by charleszipp** [comment]
@HerrHoller thanks for the suggestion. I think this would be useful in any case where the user is not using the azurerm provider in their templates.

**Comment by favoretti** [comment]
I reckon this relates to #43, so can be tackled in one go.

**Comment by charleszipp** [comment]
@favoretti will be working on a change that should accommodate this.
