### ISSUE TITLE
Error refreshing state: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by marrobi** [charleszipp/azure-pipelines-tasks-terraform#56]
Hello,

This error has suddenly started appearing and can;t get to the root cause. The task is successfully creating the storage account and container - so service connection is correct -  but fails when creating the backend:

```
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

Has anyone seen this before? Thanks.

**Comment by charleszipp** [comment]
@marrobi are you still having this issue? If so can you upload the entire pipeline log for terraform init?

**Comment by TME520** [comment]
@charleszipp Hello, I have the same issue.

Here is the output from the task in Azure DevOps pipeline:

---8<------
[command]C:\hostedtoolcache\windows\terraform\0.11.13\x64\terraform.exe init -backend-config=storage_account_name=terraform4uat -backend-config=container_name=sad-panda-dev-backend-config=key=dev.terraform.state -backend-config=resource_group_name=sad-panda-dev -backend-config=arm_subscription_id=****** -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=***

Initializing the backend...‌

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.‌
Error refreshing state: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.‌
RequestId:******
Time:2019-09-02T05:52:36.1126027Z, RequestInitiated=Mon, 02 Sep 2019 05:52:35 GMT, RequestId=d7cb9bee-e01e-00ba-7752-612955000000, API Version=, QueryParameterName=, QueryParameterValue=‌
##[debug]set TERRAFORM_LAST_EXITCODE=1
##[debug]Processed: ##vso[task.setvariable variable=TERRAFORM_LAST_EXITCODE;issecret=false;]1
##[debug]task result: Failed
##[error]Terraform command 'init' failed with exit code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Terraform command 'init' failed with exit code '1'.
##[debug]Processed: ##vso[task.complete result=Failed;]Terraform command 'init' failed with exit code '1'.
##[section]Finishing: terraform init
---8<------

Is it an issue on my side or is there anything wrong with your product ?

Do not hesitate to ask for more information / traces.

Thanks

**Comment by charleszipp** [comment]
@TME520 @marrobi is this issue still occurring? If so can you send screenshot of how the service connection is configured? Please redact the values set in the fields. I only need to see what fields are set.

Closing for now, will reopen if response received from the reporters.
