### ISSUE TITLE
environmentServiceName

### ISSUE THREAD

**Issue by FirstInternetUser** [charleszipp/azure-pipelines-tasks-terraform#58]
When running the terraform plan, the following error is thrown:

##[error]Error: Input required: environmentServiceName
##[section]Finishing: terraform plan

What is causing this? The init, and validate prior to the plan section works fine.

I am using Azure DevOps to deploy to AWS

**Comment by charleszipp** [comment]
@FirstInternetUser 
Can you post a screen shot of the task inputs/setup you are using when hitting this error? Also, which version of terraform are you using? You can redact the sensitive input values if needed. 

My suspicion is that the selection for your azure subscription is some how missing. Perhaps theres an old value there and the service connection to which its associated has been removed?

**Comment by FirstInternetUser** [comment]
I'm using version 0.11.14.

This might be a silly question but I am trying to use Azure DevOps to deploy to **AWS**. I didn't enter an Azure subscription. I thought this was for Azure deployments only.

**Comment by charleszipp** [comment]
The task doesn't currently support deployments to AWS. So that is probably why you are getting this error.
