### ISSUE TITLE
Enhancement: Allow Version: "latest" during Terraform Installer Task  

### ISSUE THREAD

**Issue by iharrington** [charleszipp/azure-pipelines-tasks-terraform#60]
![image](https://user-images.githubusercontent.com/43457037/58922675-c496c900-86f0-11e9-8d10-b6430d6c5ebb.png)
I tried using "latest" in the Version field but the task fails, apparently it only accepts hard-coded values like picture provided.

**Comment by iharrington** [comment]
`##[error]Error: The input version 'latest' is not a valid semantic version`

**Comment by charleszipp** [comment]
Thanks @iharrington for your feedback. Unfortunately, this was not implemented earlier as terraform does not provide a url for latest release. You can see more about why [here](https://github.com/hashicorp/terraform/issues/9803). Fortunately, that same post shares a way we can determine the latest using checkpoint api. We could invoke this to determine latest if the users leaves version blank or uses "latest"

**Comment by charleszipp** [comment]
Released with 0.5.4
