### ISSUE TITLE
Push terraform output values to azure pipeline variables

### ISSUE THREAD

**Issue by ksix** [charleszipp/azure-pipelines-tasks-terraform#62]
Could you add a terraform output task that hydrates outputs as Azure DevOps pipeline variables? I know there are other extensions that do this, but having all the terraform tasks provided as a single extension would be nice.

**Comment by charleszipp** [comment]
@ksix Thanks for the suggestion. This seems like it would be a better fit for a custom terraform provider than trying to bake this into the azure devops extension. If we were to use the output command, this would cause the values to show in the pipeline logs. Additionally, the values that are marked secret and redacted would not be accessible to the extension.

If this were a terraform provider, the provider would have access to the values without using outputs/logs. It could then also keep track of the variables and their values in their state. I would suggest opening this up to the terraform community on their github. Alternatively, it seems theres an opportunity for a new OSS project to create this provider.

**Comment by nmiodice** [comment]
@AdamCoulterOz I'm not sure if this is relevant for you anymore, but there is an effort to build a Terraform provide for Azure DevOps. Here is our design story to support AzDO variable groups...

https://github.com/microsoft/terraform-provider-azuredevops/issues/21

**Comment by charleszipp** [comment]
will be fixed with #120
