### ISSUE TITLE
Configuration Directory doesn't seem to work on Terraform CLI task

### ISSUE THREAD

**Issue by Thitou** [charleszipp/azure-pipelines-tasks-terraform#65]
Hi,

In my Pipeline deployment service, I'm trying to do the following:
- Extract the terraform files from a published build in in the destination folder : $(Agent.ReleaseDirectory)/Copernic/tfplan/Payload
- Use the Terraform CLI task to run the terraform init command in that directory.

![Task](https://user-images.githubusercontent.com/34694382/61312612-0d19ca00-a7f9-11e9-9d56-ce1e7892b4a0.PNG)

I'm assuming that the "Configuration Directory" setting is the directory where you want to run the terraform command. However, I keep getting the "terraform initialized in an empty directory!" error.

Command is ran in /usr/local/bin/terraform when I don't use the terraform version task on Ubuntu agent

![result](https://user-images.githubusercontent.com/34694382/61312611-0d19ca00-a7f9-11e9-96b8-ed4057152724.PNG)

Can you please advise whether I'm making a good use of this task or not? 

Cheers

**Comment by charleszipp** [comment]
@Thitou can you rerun the release stage with the debug flag enabled. Please attach the log here.

**Comment by charleszipp** [comment]
Closing as there has been no response on this for several months
