### ISSUE TITLE
Save output from terraform plan to file (not the plan file itself)

### ISSUE THREAD

**Issue by toorog** [charleszipp/azure-pipelines-tasks-terraform#84]
I use this task in a release pipeline. Before the actual deployment happens, someone does a manual Review and then approves the check. For this purpose it would be great to be able to write the diff output that is produced during a `terraform plan` to a file, so that this can then be attached as a build artefact.

**Comment by charleszipp** [comment]
@toorog You should be able to do this today by providing the `-out` option with a path in the command options field when running the plan command. This should write the plan file do a directory you specify on the build agent. You could then use the Copy & Publish tasks to include the file as part of the build artifacts.

https://www.terraform.io/docs/commands/plan.html#out-path

![image](https://user-images.githubusercontent.com/4292559/66914385-50dcc500-efdc-11e9-9b63-b2729cca582b.png)

**Comment by toorog** [comment]
@charleszipp This is not about the terraform plan, since it is not readable by a human it is not something that can be reviewed. Instead I'd like to have the output that `terraform plan` writes to stdout available in a file.

**Comment by charleszipp** [comment]
@toorog understood, i have reopened the issue labeled appropriately

**Comment by charleszipp** [comment]
@toorog if we add support for the `show` command where the plan can be written to readable file, would that satisfy your use case? If not, can you provide explanation as to why it wouldnt?

Related #104

**Comment by toorog** [comment]
@charleszipp If 'readable' is defined as 'readable by a human' (textual output) then yes.

**Comment by charleszipp** [comment]
@toorog thanks for responding and clarifying. Yes the output would be readable by a human. #104 should allow that by making `terraform show -json my-plan.tfplan` something you can run from the TerraformCLI task. That should result in a human-readable, json formatted plan file.

Closing this as it will be solved with #104.
