### ISSUE TITLE
not able to login the subscription using service principal

### ISSUE THREAD

**Issue by hugo-zhang-uipath** [charleszipp/azure-pipelines-tasks-terraform#85]
##[section]Starting: Terraform init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.4.13
Author       : Charles Zipp
Help         : 
==============================================================================
[command]/opt/hostedtoolcache/terraform/0.12.7/x64/terraform version
Terraform v0.12.7
[command]/usr/bin/az login --service-principal -t *** -u *** -p ***
ERROR: No subscriptions were found for '***'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses
##[error]Error: ERROR: No subscriptions were found for '***'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses

##[section]Finishing: Terraform init

Hi, I am facing this issue, and I am sure I use the correct client id, client secret and tenant id. I can use the same client secret and tenant id to login my subscription from my local computer. Does anyone meet this issue? Thanks!

**Comment by charleszipp** [comment]
@hugo-zhang-uipath if this is still an issue please reply here and attach full log while with system.debug pipeline variable set to true.
