### ISSUE TITLE
This VS microsoft version

### ISSUE THREAD

**Issue by gjcampbell** [charleszipp/azure-pipelines-tasks-terraform#88]
Hi, do you have a recommendation whether to use this extensions versus the [microsoft terraform extension](https://github.com/microsoft/azure-pipelines-extensions/tree/master/Extensions/Terraform/Src)? 

I saw that you work for MS. Did you work on MS's [terraform ADO extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)? 

BTW, this extension's TerraformInstall task and the one from MS have identical names and having both extensions causes a conflict.

**Comment by charleszipp** [comment]
Hey @gjcampbell, to be honest i was not aware of the other extension. It looks like that was created only a few months ago. I would recommend evaluating which suites your needs best. It appears that the other supports deployments to other cloud providers than azure. If you need to deploy to AWS or Google, that may be a good reason to use the other.

As a side note, I am trying to work on transitioning this extension to a microsoft dev team. I am hoping this transition will happen before the end of the year. If that is successful then this should have a full time dev team. I would imagine these would eventually be converged after that point.

Hopefully that helps. Let me know if you have any other questions.
