### ISSUE TITLE
terraform cli task failing with exit code null

### ISSUE THREAD

**Issue by ausfestivus** [charleszipp/azure-pipelines-tasks-terraform#92]
I have a YAML build pipeline which is doing a simple
* grab code from repo
* terraform install task
* terraform init
* terraform validate

terraform install task completes without error.

terraform init says:
```shell
##[debug]exec tool: /opt/hostedtoolcache/terraform/0.12.13/x64/terraform
##[debug]arguments:
##[debug]   version
/opt/hostedtoolcache/terraform/0.12.13/x64/terraform version
##[debug]set TERRAFORM_LAST_EXITCODE=1
##[debug]Processed: ##vso[task.setvariable variable=TERRAFORM_LAST_EXITCODE;issecret=false;]1
##[debug]task result: Failed
##[error]Terraform command 'version' failed with exit code 'null'.
```

A gist of the full debug from ADO is at https://gist.github.com/ausfestivus/0c45476253ff1370cba15a9aaff9d4a2

Im not sure whats going on here.

I have also tested this using the same tasks strung together in the GUI and get exactly the same result.

**Comment by femiajayi** [comment]
I had a similar issue. I replaced the `task: TerraformCLI@0` with an inline script to execute `terraform init`.  I got `##[error]Not found workingDirectory: /home/vsts/work/1/s/my-path/...`. This made me realise that my working directory was not valid. 'my-path' does not exist. I'm guessing that your `/home/vsts/work/1/s/terraform/environments/development/` does not exist, If you update your working directory, it should work.

**Comment by ausfestivus** [comment]
Hey @femiajayi 
You're spot on, working path didn't exist. Thank you.

Would be nice if the tasks were able to output meaningful errors like this. Unsure why it didnt/doesnt.

Closing.
