### ISSUE TITLE
add support for `refresh` command

### ISSUE THREAD

**Issue by ausfestivus** [charleszipp/azure-pipelines-tasks-terraform#93]
Afternoon,

Can we please have support for the `refresh` command option added?

I am using Azure DevOps YAML pipelines to do the build, deploy and destroy of non-prod environments. I have a very long running `destroy` task that more often than not fails due to a timeout.

Till the AzureRM provider 2.0 is released and broader support for timeouts is available (which may or may not actually fix the underlying issue here), I am having to re-run the destroy stage of the pipeline. I would like to run a `refresh` prior to the delete in case a previous delete stage run has failed and left the shared state in an inconsistent state.

**Comment by mfilotto** [comment]
+1
OU CI/CD would be more robust with a refresh first.

**Comment by charleszipp** [comment]
Will be released with 0.5.5
