### ISSUE TITLE
Azure DevOps extension is hanging on init step

### ISSUE THREAD

**Issue by N1k05** [charleszipp/azure-pipelines-tasks-terraform#94]
Azure DevOps extension is hanging on init step and I am getting following error in task logs.

ApplicationInsights:Sender [ 'Not saving data due to max size limit being met. Directory size in bytes is: 50001849' ]

Have you come across it before?

**Comment by charleszipp** [comment]
Hey @N1k05, I have not observed this issue before. Can you let me know if this is still occurring? What type of build agent is being used? Is the agent disk space full? 

Closing for now. Will reopen if reported as still being an issue.
