### ISSUE TITLE
What is a way to specify custom CLI Configuration File

### ISSUE THREAD

**Issue by borys86** [charleszipp/azure-pipelines-tasks-terraform#95]
We are using our private terraform registry and we need to add authentication config. 
In a local environment, we can follow this documentation and create needed CLI Configuration File.
How would you recommend to deal with it in a pipeline so terraform executable is aware of it.
I guess we could generate this file and put it default execution path but how to tell terraform about it existence? 

https://www.terraform.io/docs/commands/cli-config.html

**Comment by charleszipp** [comment]
Hey @borys86 

The documentation link you included references that it is possible to override the default expected location of this config file using an environment variable [TF_CLI_CONFIG_FILE](https://www.terraform.io/docs/commands/environment-variables.html#tf_cli_config_file) . Have you tried to generate the file ahead of the terraform steps in the pipeline and then use the environment variable to make terraform aware of the generated file?

Another more sophisticated alternative may be to leverage the secure files library in azure devops to host the config file. Then, update the extension to have a field where you can reference the config file to use from the secure files library. 

The first option may be a good way to work around this for now. However, please let me know what you think of the second one as a potential enhancement and if you had other thoughts about what that enhancement might look like.

**Comment by ryancbutler** [comment]
I used the **TF_CLI_CONFIG_FILE** approach in the following manner.

1. Created a blank **terraform.rc** file and saved to my terraform repo
```
credentials "app.terraform.io" {
  token = "__TFETOKEN__"
}
```
2. Created a **TFETOKEN** variable on the pipeline with the TFE user token
3. Created a Replace Token task in the stage that focuses on rc files 
4. Created a **TF_CLI_CONFIG_FILE** variable to `$(System.DefaultWorkingDirectory)/{alias}/terraform.rc`
5. Now able to use private modules

**Comment by charleszipp** [comment]
Thanks @ryancbutler for providing this approach. I am closing this down as there are multiple suggested path ways to do this.
