### ISSUE TITLE
Add support for TF_VAR_ environment variables and .env files 

### ISSUE THREAD

**Issue by rguthriemsft** [charleszipp/azure-pipelines-tasks-terraform#97]
The project we are working on uses TF_VAR env variables instead of TF_VARS file.  currently when the task runs it doesn't apply TF_VARS variables on agent.  We want to be able to pass location of .env file and have tF task add the values to env so that terraform command will see them when executing terraform commands.

We plan to add support into the task using dotenv library.

**Comment by charleszipp** [comment]
Hey @rguthriemsft this sounds like a great feature. I would recommend the .env still be managed via secure files. Since that will likely contain secrets, the secure files library ensures its only readable by those that have been authorized to do so.

**Comment by charleszipp** [comment]
@rguthriemsft according to the code docs in `azure-pipelines-task-lib.ToolRunner`, it should use the current process' env vars when it spawns the child process to run the terraform executable. Therefore, I believe if you can download the .env from the secure files library and set the agent's env vars using that, it should cascade to the child process.

If that doesnt work, then you could add a new property to the base class `TerraformCommand` for a key-value object. Within the apply command class, set that object with the appropriate env vars. Then, in TerraformRunner, set IExecSyncOptions.env with this object when calling `execSync`. See line 140 on terraformcli/src/terraform-runner.ts.

**Comment by charleszipp** [comment]
released with 0.4.16
